### ISSUE TITLE
希望能多提供一下demo代码，比如演示怎么用协程api实现网络程序

### ISSUE THREAD

**Issue by xwpcom** [idealvin/co#1]
比如实现http下载网页或文件

谢谢!

**Comment by idealvin** [comment]
协程提供的网络 api 用法跟普通的 socket api 几乎一样，pdf 参考文档里有个简单的 tcp server/client 示例，不能满足你的需求吗？

**Comment by idealvin** [comment]
可以参考 [base/rpc](https://github.com/idealvin/co/blob/master/base/rpc.cc) 的实现代码

**Comment by xwpcom** [comment]
测试了文档中的go(client_fun)
效果很好，非常感谢

**Comment by namzin** [comment]
code
