### ISSUE TITLE
能否给个CMAKE的编译脚本

### ISSUE THREAD

**Issue by neo1986** [idealvin/co#10]
能否给个CMAKE的编译脚本，最好在alpine的环境下也能编译通过，github上很多库我在制作alpine镜像时候都碰到各种问题

**Comment by idealvin** [comment]
我不会写cmake呢，甚至makefile也不会，希望能提一个pr，如果有问题，我这边可以配合一下，大致可以参考co/base下的scons脚本

**Comment by daidai21** [comment]
需要生成静态链接库和动态链接库的脚本吗还是？ @idealvin

**Comment by idealvin** [comment]
支持静态库就可以了

**Comment by daidai21** [comment]
https://github.com/idealvin/co/blob/2f9a5912d4148cf065fada70352b58d77a04613b/base/stack_trace/StackWalker.cpp#L89
https://github.com/idealvin/co/blob/2f9a5912d4148cf065fada70352b58d77a04613b/base/stack_trace/StackWalker.cpp#L90

g++编译错误，头文件包含没理清楚...

```shell
find base/ -regex ".*[cpp|cc]" | xargs g++ -c -D _WIN32=false
```
求指教

**Comment by idealvin** [comment]
.cpp是 &nbsp;windows的，
.cc 是 linux/mac的



---原始邮件---
发件人: "Daidai"<notifications@github.com&gt;
发送时间: 2019年12月5日(星期四) 晚上8:46
收件人: "idealvin/co"<co@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Alvin"<idealvin@qq.com&gt;;
主题: Re: [idealvin/co] 能否给个CMAKE的编译脚本 (#10)



https://github.com/idealvin/co/blob/2f9a5912d4148cf065fada70352b58d77a04613b/base/stack_trace/StackWalker.cpp#L89
 https://github.com/idealvin/co/blob/2f9a5912d4148cf065fada70352b58d77a04613b/base/stack_trace/StackWalker.cpp#L90
 
g++编译错误，头文件包含没理清楚...
 find base/ -regex ".*[cpp|cc]" | xargs g++ -c -D _WIN32=false
 
求指教

**Comment by idealvin** [comment]
.cpp是windows的文件，不要加进去



---原始邮件---
发件人: "Daidai"<notifications@github.com&gt;
发送时间: 2019年12月5日(星期四) 晚上8:46
收件人: "idealvin/co"<co@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Alvin"<idealvin@qq.com&gt;;
主题: Re: [idealvin/co] 能否给个CMAKE的编译脚本 (#10)



https://github.com/idealvin/co/blob/2f9a5912d4148cf065fada70352b58d77a04613b/base/stack_trace/StackWalker.cpp#L89
 https://github.com/idealvin/co/blob/2f9a5912d4148cf065fada70352b58d77a04613b/base/stack_trace/StackWalker.cpp#L90
 
g++编译错误，头文件包含没理清楚...
 find base/ -regex ".*[cpp|cc]" | xargs g++ -c -D _WIN32=false
 
求指教

**Comment by idealvin** [comment]
makefile  cmake 语法过于复杂，作者表示看不懂。
请使用 [xmake](https://github.com/xmake-io/xmake/releases) 或 [scons](http://scons.org/) 编译。

**Comment by idealvin** [comment]
用xmake吧，make、cmake有些繁琐



---原始邮件---
发件人: "Daidai"<notifications@github.com&gt;
发送时间: 2019年12月5日(星期四) 晚上8:46
收件人: "idealvin/co"<co@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Alvin"<idealvin@qq.com&gt;;
主题: Re: [idealvin/co] 能否给个CMAKE的编译脚本 (#10)



https://github.com/idealvin/co/blob/2f9a5912d4148cf065fada70352b58d77a04613b/base/stack_trace/StackWalker.cpp#L89
 https://github.com/idealvin/co/blob/2f9a5912d4148cf065fada70352b58d77a04613b/base/stack_trace/StackWalker.cpp#L90
 
g++编译错误，头文件包含没理清楚...
 find base/ -regex ".*[cpp|cc]" | xargs g++ -c -D _WIN32=false
 
求指教
