### ISSUE TITLE
有支持unicode的计划吗

### ISSUE THREAD

**Issue by sankeyou** [idealvin/co#11]
有支持unicode的计划吗? 或其提供编码转换的类?

**Comment by zzzhr1990** [comment]
必要性好像不太大，毕竟为了兼容Windows这个辣鸡要多弄一套wchar*的东西出来

**Comment by be5invis** [comment]
@zzzhr1990 
Keep interanal storage in `char8_t*` and convert into WSTR-ish thingy before calling WINAPI is a solution. Many libraries are using that.

**Comment by be5invis** [comment]
Also, extending `fastring` to support other kinds of "character" types (like `char16_t`, `char32_t`), may look helpful.

**Comment by sgf** [comment]
> 必要性好像不太大，毕竟为了兼容Windows这个辣鸡要多弄一套wchar*的东西出来
I don't know why,but you let the Unicode and windows equated?

**Comment by sgf** [comment]
Unicode support for multiple languages and internationalization very helpful.

**Comment by sgf** [comment]
WTL  91_5321 版本 有个CString可以看下。

**Comment by idealvin** [comment]
不支持
