### ISSUE TITLE
windows 上 dll 调试模式下程序崩溃，Debug Assertion Failed!

### ISSUE THREAD

**Issue by a952135763** [idealvin/co#115]
只要我使用 co::sleep 函数就会报错
co 使用cmake 编译得 然后引入了 头文件 和LIB文件 
使用官方的 client 代码示例

`

    sock_t fd = co::tcp_socket();
    struct sockaddr_in addr;
    co::init_ip_addr(&addr, "127.0.0.1", 7788);
    co::connect(fd, &addr, sizeof(addr), 3000);
    co::set_tcp_nodelay(fd);
    char buf[8] = { 0 };
    for (int i = 0; i < 7; ++i) {
        co::sleep(1000);
        LOG << "send ping";
        co::send(fd, "ping", 4);
        co::recv(fd, buf, 4);
        LOG << "recv " << buf;
    }
    co::close(fd);

`

co::connect 填写第4个参数会报错 崩溃
co::sleep 也会报错 崩溃

错误提示
Debug Assertion Failed!

Program: E:\fiber\exiecheng\coroutine\Debug\testdll.exe
File: D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.26.28801\include\xtree
Line: 229

Expression: map/set iterators incompatible

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

**Comment by idealvin** [comment]
@a952135763 

> sock_t fd = co::tcp_socket();
> struct sockaddr_in addr;
> co::init_ip_addr(&addr, "127.0.0.1", 7788);
> co::connect(fd, &addr, sizeof(addr), 3000);
> co::set_tcp_nodelay(fd);
> char buf[8] = { 0 };
> for (int i = 0; i < 7; ++i) {
>     co::sleep(1000);
>     LOG << "send ping";
>     co::send(fd, "ping", 4);
>     co::recv(fd, buf, 4);
>     LOG << "recv " << buf;
> }
> co::close(fd);

上面这些是在协程中执行的吗？

**Comment by idealvin** [comment]
[test/so/tcp.cc](https://github.com/idealvin/co/blob/master/test/so/tcp.cc) 上有示例，执行

```sh
xmake -b tcp
xmake r tcp
```

看看能不能正常运行？

**Comment by a952135763** [comment]
是在协程中执行的
我编译下测试例子试试

**Comment by a952135763** [comment]
呃 是用cmake 生成的 我没用 xmake
test/so/tcp.cc  的测试例子也没法正常运行 生成配置 是X86-Debug 
但是我用 X86-Release 生成的例子又能正常运行

**Comment by idealvin** [comment]
@a952135763 
看样子是编译环境的问题。在 windows 上建议用 xmake 编译，或直接用 vs 编译，不建议用 cmake。

**Comment by a952135763** [comment]
知道问题所在了
使用Mtd MDd编译
都会出现这个错误
也就是没法使用debug模式调用库.............

**Comment by idealvin** [comment]
> 知道问题所在了
> 使用Mtd MDd编译
> 都会出现这个错误
> 也就是没法使用debug模式调用库.............

可能是因为编译 libco  时就没有加 Mtd  MDd 吧..

**Comment by a952135763** [comment]
> > 知道问题所在了
> > 使用Mtd MDd编译
> > 都会出现这个错误
> > 也就是没法使用debug模式调用库.............
> 
> 可能是因为编译 libco 时就没有加 Mtd MDd 吧

加了就会出现我说的错误哦 测试例子直接过不到

**Comment by idealvin** [comment]
@a952135763 
hi, 最近抽时间用 vs 调试了这个问题，发现MTd, MDd模式下，即 DLL 调试模式下， std::multimap 的 iterator 与 co 中 null_timer_id 进行比较操作时会 assert failed. 已经修复此问题，详情见[这里](https://github.com/idealvin/co/commit/51e30764111d3efd291c3adb24542916275cc519).
