### ISSUE TITLE
jsonrpc部分的Go语言绑定

### ISSUE THREAD

**Issue by chenshaxiong** [idealvin/co#117]
如题, 即使不能全功能,  是否考虑在example中提供 go java 语言作为客户端的例子.

**Comment by chenshaxiong** [comment]
2个想法:
1. rpc部分的例子是否可以改进, 以提供符合 jsonrpc 1.0 , jsonrpc 2.0 规范的例子. 在错误处理方面适当简化即可.
2. 传输部分目前基于tcp, 是否考虑扩展支持 http

**Comment by idealvin** [comment]
> 2个想法:
> 
> 1. rpc部分的例子是否可以改进, 以提供符合 jsonrpc 1.0 , jsonrpc 2.0 规范的例子. 在错误处理方面适当简化即可.
> 2. 传输部分目前基于tcp, 是否考虑扩展支持 http

@chenshaxiong 嗯，这一块后续会重构，如果有人愿意贡献代码的话，那更好

**Comment by chenshaxiong** [comment]
最近做了一组 github.com/ybbus/jsonrpc 调用 libjsonrpc-cpp 的接口.
可以考虑升级一下rpc接口规范, 统一到 jsonrpc 2.0, (感觉这块改动不会大), 这样其它语言的例子就不必在本仓库专门做了.
http支持比较有吸引力, 在不是特别强调性能的场合, jsonrpc-over-http 生态比较丰富

**Comment by idealvin** [comment]
@chenshaxiong 嗯，这个后续会考虑的

**Comment by daidai21** [comment]
@idealvin 
要不你大概定下接口？我试着写下jsonrpc这块的功能？怎么样？

**Comment by idealvin** [comment]
@daidai21 如果能弄个邮件列表沟通，就比较好..

**Comment by idealvin** [comment]
@all  
利用163邮箱创建了一个邮件列表，有兴趣的可以通过下面的链接加入，[http://163.fm/V2pUcEg9](http://163.fm/V2pUcEg9)，支持非 163 邮箱.

**Comment by idealvin** [comment]
目前考虑在 tcp server 的基础上，抽象出一层应用层协议，以支持 http1.x，http2.0, ssl, https, rpc 等，有兴趣的可以加入邮件列表讨论

**Comment by idealvin** [comment]
co/rpc 的目标是提供一个类似 grpc 或 thrift 的 RPC 框架，只不过内部用 JSON 数据格式取代了 protobuf 或 thrift 协议。它与上面提到的 jsonrpc 不同。
