### ISSUE TITLE
如何更改配置的值

### ISSUE THREAD

**Issue by tiantianaixuexi** [idealvin/co#119]
类似于文档的这种 日志输出的位置，日志文件名字，应该如何设置呢？

`//日志打印输出的位置
DEF_string(log_dir, "../log", "Log dir, will be created if not exists");
//日志文件名
DEF_string(log_file_name, "acl_log", "name of log file, using exename if empty");
//日志打印级别
DEF_int32(min_log_level, 0, "write logs at or above this level, 0-4 (debug|info|warning|error|fatal)");
//输出到终端
DEF_bool(cout, true, "also logging to terminal");

DEF_int32(co_sched_num, 100, "协程栈大小，每个调度线程都会分配一个栈，调度线程内的协程共用这个栈。");
DEF_int32(co_max_recv_size, 2, "一次能接收的最大数据长度，默认为 1M，超过此大小，分批接收。");
DEF_int32(co_max_send_size, 2, "一次能发送的最大数据长度，默认为 1M，超过此大小，分批发送");`

**Comment by idealvin** [comment]
@tiantianaixuexi 可以看看 [参考文档](https://idealvin.github.io/coding/2020/07/co/) 里的第9、10章
