### ISSUE TITLE
rpc test失败

### ISSUE THREAD

**Issue by j7252008** [idealvin/co#12]
环境：vs2019
问题：运行rpc test程序时出现错误map/set iterators incompatible

**Comment by idealvin** [comment]
有详细的信息吗? 截图?

**Comment by j7252008** [comment]
> 有详细的信息吗? 截图?


![批注 2019-11-30 233915](https://user-images.githubusercontent.com/13350543/69902589-a3c2de00-13ca-11ea-8d51-dee3f50275f2.png)，Debug版的有问题，Release的测试正常

**Comment by idealvin** [comment]
vs2015目录下的项目只有release版本，没有debug版的，如果要编译debug版，可能需要自行设置工程属性

**Comment by j7252008** [comment]
> vs2015目录下的项目只有release版本，没有debug版的，如果要编译debug版，可能需要自行设置工程属性

对的，我是自己新建的debug版，请问需要设置哪些特殊的吗？

**Comment by idealvin** [comment]
请问你的debug版是怎么编译出来的？

**Comment by j7252008** [comment]
新建了Debug配置，其他默认的

**Comment by idealvin** [comment]
你能仔细对比一下release版与debug版的工程属性吗？与release保持一致试试

**Comment by j7252008** [comment]
不行，应该是编译选项的问题，我先用Release的吧
