### ISSUE TITLE
致歉：作者准备换行，后续不再参与此项目的开发工作

### ISSUE THREAD

**Issue by idealvin** [idealvin/co#121]
Hi, all,

很抱歉的通知大家，作者([idealvin](https://github.com/idealvin))近来厌倦了各种995、996、007，决定换个行业，另谋生路，不再参与本项目的后续开发工作。

如果不出意外，作者今后不会再写代码了，但仍然考虑提供一些有偿的技术支持服务。

有意接手此项目的朋友，可以私下联系我(idealvin at qq.com)，谢谢！

**Comment by yanlinlin82** [comment]
有些可惜了。祝顺利！

**Comment by izhengfan** [comment]
无奈。祝顺利。

**Comment by dasuren** [comment]
祝顺利。

**Comment by mt21625457** [comment]
祝顺利。。

**Comment by idealvin** [comment]
呃，我又回来了，难与命争，再写两年代码看看...

**Comment by waruqi** [comment]
额。。。

**Comment by notedit** [comment]
> 呃，我又回来了，难与命争，再写两年代码看看...

哈哈

**Comment by Justme0** [comment]
> 呃，我又回来了，难与命争，再写两年代码看看...

haha

**Comment by zhwaaaaaa** [comment]
old brother, how old are you?

**Comment by sdutwsl** [comment]
哈哈哈哈哈 人间真实
