### ISSUE TITLE
win10 test co.cc 报错

### ISSUE THREAD

**Issue by xiaoyi971520** [idealvin/co#125]
43行  go(f3);

---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Assertion Failed!

Program: E:\_work\myco\build\bin\co.exe
File: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\xmemory
Line: 1196

Expression: ITERATOR LIST CORRUPTED!

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

---------------------------
中止(A)   重试(R)   忽略(I)

**Comment by idealvin** [comment]
@xiaoyi971520  用 release 版本试试

**Comment by uniqss** [comment]
为什么debug会崩呢？

**Comment by idealvin** [comment]
@uniqss
我这边用 vs2019, debug x64 编译是正常的，程序运行也正常
```sh
alvin@Envy /d/cc/co/build/windows/x64/debug (dev)
$ ./co.exe
D:\cc\co\test\co.cc:27] f2() r: false
D:\cc\co\test\co.cc:31] f3()
D:\cc\co\test\co.cc:14] f1()
D:\cc\co\test\co.cc:14] f1()
D:\cc\co\test\co.cc:14] f1()
D:\cc\co\test\co.cc:14] f1()
D:\cc\co\test\co.cc:14] f1()
D:\cc\co\test\co.cc:14] f1()
D:\cc\co\test\co.cc:14] f1()
D:\cc\co\test\co.cc:14] f1()
D:\cc\co\test\co.cc:47] v: 8
D:\cc\co\test\co.cc:48] n: 8
```

**Comment by idealvin** [comment]
可能与 #115 是同一个问题

> 知道问题所在了
> 使用Mtd MDd编译
> 都会出现这个错误
> 也就是没法使用debug模式调用库.............

**Comment by idealvin** [comment]
@xiaoyi971520 @uniqss 

已修复此问题，详情见[这里](https://github.com/idealvin/co/commit/51e30764111d3efd291c3adb24542916275cc519).

windows 在 dll 调试模式下，std::multimap 的 iterator 在进行比较操作时，会进行严格的检查，导致 assert failed.
