### ISSUE TITLE
fastream 不支持 << std::endl

### ISSUE THREAD

**Issue by tiantianaixuexi** [idealvin/co#126]

**Comment by idealvin** [comment]
@tiantianaixuexi  有这种需求吗？用 '\n' 就可以吧

**Comment by tiantianaixuexi** [comment]
确实，哈哈

**Comment by tiantianaixuexi** [comment]
aa

**Comment by daidai21** [comment]
> @tiantianaixuexi 有这种需求吗？用 '\n' 就可以吧

如果是输入的刚好有换行呢？ 感觉还是加下endl比较好吧

**Comment by idealvin** [comment]
> > @tiantianaixuexi 有这种需求吗？用 '\n' 就可以吧
> 
> 如果是输入的刚好有换行呢？ 感觉还是加下endl比较好吧

@daidai21  用 '\n' 换行，std::endl 是个模板函数，没办法传给 fastream
