### ISSUE TITLE
fastring 使用<< 后面会多加乱码

### ISSUE THREAD

**Issue by tiantianaixuexi** [idealvin/co#130]
![( PTGTHCT)U5HPJW5V{O}K4](https://user-images.githubusercontent.com/31758095/107979413-6c802300-6fb6-11eb-9e1c-e875bc999489.png)

data.memid 类型是 unsigned long long

**Comment by idealvin** [comment]
@tiantianaixuexi  fastring 内部不一定是 '\0' 结尾，上面的显示可能是正常的，你可以打印出fastring 内容及长度看看

**Comment by tiantianaixuexi** [comment]
> @tiantianaixuexi fastring 内部不一定是 '\0' 结尾，上面的显示可能是正常的，你可以打印出fastring 内容及长度看看

打印出来是正常的，mysql也没有报错，可是mysql update却没有效果。

**Comment by idealvin** [comment]
@tiantianaixuexi 你是怎么用的?

**Comment by tiantianaixuexi** [comment]
就很简单的 update,像图中的一样.

            fastring aaa;
		aaa<<"UPDATE user_member set "<<"username='"<<data.nick<<"',"<<"sex="<<(int)data.sex<<" where id="<<(int)data.memid;
	
		auto mysql = db->GetMysqlConnector();
		const int err = mysql->ExecQuery(aaa.str());
		if (err != 0)
		{
			LOG_MSG("ChooseNick error:%d-%d-%s  line:%d\n", err, mysql->GetErrorCode(), mysql->GetErrorStr(), __LINE__);
		}

mysql->ExecQuery(aaa.str()); 里面封装的是

`
  int  nRet = mysql_real_query(mysql, pData.c_str(), pData.length());
`

使用 stringstream 更新结果是正常的，使用 fastring 不会报错，但是更新没有反应，不知道是不是mysql的问题..

**Comment by idealvin** [comment]
@tiantianaixuexi  fastring 应该没有 .str() 这个操作吧？

**Comment by tiantianaixuexi** [comment]
> @tiantianaixuexi fastring 应该没有 .str() 这个操作吧？

.c_str()      .str() 是 stringstream的。那个是伪代码

**Comment by idealvin** [comment]
用 .c_str() 应该是可以的
