### ISSUE TITLE
协程库和网络库重定义的错误如何处理

### ISSUE THREAD

**Issue by iwasaboy** [idealvin/co#138]
#include "co.h"
#include "so.h"

d:\windows kits\10\include\10.0.17763.0\shared\ws2def.h(103): warning C4005: “AF_IPX”: 宏重定义
1>d:\windows kits\10\include\10.0.17763.0\um\winsock.h(457): note: 参见“AF_IPX”的前一个定义
1>d:\windows kits\10\include\10.0.17763.0\shared\ws2def.h(147): warning C4005: “AF_MAX”: 宏重定义
1>d:\windows kits\10\include\10.0.17763.0\um\winsock.h(476): note: 参见“AF_MAX”的前一个定义
1>d:\windows kits\10\include\10.0.17763.0\shared\ws2def.h(185): warning C4005: “SO_DONTLINGER”: 宏重定义
1>d:\windows kits\10\include\10.0.17763.0\um\winsock.h(399): note: 参见“SO_DONTLINGER”的前一个定义
1>d:\windows kits\10\include\10.0.17763.0\shared\ws2def.h(235): error C2011: “sockaddr”:“struct”类型重定义
1>d:\windows kits\10\include\10.0.17763.0\um\winsock.h(1007): note: 参见“sockaddr”的声明

包含co.h或者so.h就会报错大量的重定义  请问这个怎么处理呢

**Comment by idealvin** [comment]
@iwasaboy 
你是在 .h 文件里包含的？然后开头还没有加 #pragma once 这样的保护？

**Comment by iwasaboy** [comment]
> @iwasaboy
> 你是在 .h 文件里包含的？然后开头还没有加 #pragma once 这样的保护？

就是再主文件（test.cpp）中 直接包含
#include "co/all.h"

**Comment by idealvin** [comment]
用 master 最新代码，执行下面的命令重新编译一下：
```cpp
rm -rf .xmake
xmake -a
```

**Comment by idealvin** [comment]
co 的目录结构：
```cpp
co/include/co/*.h
co/src
```

建议将 co/include 加到编译器的包含目录，在代码中使用：
```cpp
#include "co/so.h"
#include "co/co.h"
```

你可能是将 co/include 与 co/include/co 一并加到了包含目录...
