### ISSUE TITLE
[help] co::go(): any easy and efficient way to send notices to all schedulers and/or all coroutines?

### ISSUE THREAD

**Issue by DisableAsync** [idealvin/co#142]
i have a program like this

```
server.listen();
while (server.poll())
    go([socket = socket.acceptConnection()]() mutable {
        char bytes[1024];
        while (int size = socket.receive(bytes, 1024))
        {
            // do something and write to socket
        }
    });
```

this works perfectly for request-response pattern.
but in situations where server push is also desired (like in subscribe-publish pattern, but work with request-response at the same time. ), what can i do if i dont wanna open up another connection and do different things?
i dont think frequently sending "check" commands to server is a good idea.

ps: im not using `so` for networking becuz it doesnt have built-in ssl support (yet).

**Comment by DisableAsync** [comment]
just noticed the questions in body dont have much to do with that one in the title =P

**Comment by DisableAsync** [comment]
checked source code, its not hard to implement a "schedule on all schedulers" method. 
but i think i still want a "send to all coroutines" one.

**Comment by idealvin** [comment]
@DisableAsync

**Comment by DisableAsync** [comment]
@idealvin i know `co::Event`, its good. but it just wont meet my requirement xD

- we cant pass custom data alongside the event
- if we dont put the event into waiting state in time, we miss signals

**Comment by idealvin** [comment]
@DisableAsync 

So you dont want to miss a message for any subscriber. You may add a message queue for each subscriber, I guess.
When the server generates a message `std::shared_ptr<Message>`,  you send it to all the subscribers by yourself.

Every subscriber holds its own queue like `std::vector<std::shared_ptr<Message>>`, and check the messages in the queue in a coroutine.

**Comment by DisableAsync** [comment]
hmmm...

im curious, cant i just add
```
std::vector<Scheduler*> SchedManager::all() const {
    return _scheds;
}
```
and 
```
void go_all(Closure* cb) {
    for (auto&& sched : sched_mgr()->all())
        sched->add_new_task(cb);
}
```
to implement a "schedule on all schedulers" one?

SIGSEGV every time i call go_all();

**Comment by DisableAsync** [comment]
found the "problem", `Closure` is deleted in `Closure::run()`

**Comment by DisableAsync** [comment]
> So you dont want to miss a message for any subscriber. You may add a message queue for each subscriber, I guess.
> When the server generates a message `std::shared_ptr<Message>`, you send it to all the subscribers by yourself.
> 
> Every subscriber holds its own queue like `std::vector<std::shared_ptr<Message>>`, and check the messages in the queue in a coroutine.

this sounds expensive but i guess its the easiest way to achieve such a weird mechanism? 

still looking for other options tho.

**Comment by DisableAsync** [comment]
> found the "problem", `Closure` is deleted in `Closure::run()`

@idealvin 

how can i implement that `go_all()` in a more elegant way?
currently doing it in this way, it sucks:
```
void go_all(void (*f)()) {
    for (auto&& sched : sched_mgr()->all())
        sched->add_new_task(new_callback(f));
}
```

**Comment by idealvin** [comment]
@DisableAsync

You may overwrite the `go_all()` like `go()`:

```cpp
inline void go(void (*f)()) {
    go(new_closure(f));
}

inline void go(void (*f)(void*), void* p) {
    go(new_closure(f, p));
}

template<typename T>
inline void go(void (T::*f)(), T* p) {
    go(new_closure(f, p));
}

// !! Performance of std::function is poor. Try to avoid it.
inline void go(const std::function<void()>& f) {
    go(new_closure(f));
}

inline void go(std::function<void()>&& f) {
    go(new_closure(std::move(f)));
}
```

I used `std::function` only when I first designed `co::go()`, and then I found that creating object of `std::function` is rather expensive, this is why `Closure` is used..

**Comment by idealvin** [comment]
@DisableAsync 

The following is also ok:
```cpp
void go_all(void (*f)()) {
    for (uint32 i = 0; i < co::sched_num(); ++i) {
        go(f)
    }
```

**Comment by DisableAsync** [comment]
> @DisableAsync
> 
> The following is also ok:
> 
> ```c++
> void go_all(void (*f)()) {
>     for (uint32 i = 0; i < co::sched_num(); ++i) {
>         go(f)
>     }
> ```

but does this guarantee to schedule on every scheduler once and only once?

**Comment by idealvin** [comment]
> > @DisableAsync
> > The following is also ok:
> > ```c++
> > void go_all(void (*f)()) {
> >     for (uint32 i = 0; i < co::sched_num(); ++i) {
> >         go(f)
> >     }
> > ```
> 
> but does this guarantee to schedule on every scheduler once and only once?

Yes, You may see the impl of `co::go(Closure*)`:
```cpp

void go(Closure* cb) {
    sched_mgr()->next()->add_new_task(cb);
}
```

**Comment by idealvin** [comment]
> > @DisableAsync
> > The following is also ok:
> > ```c++
> > void go_all(void (*f)()) {
> >     for (uint32 i = 0; i < co::sched_num(); ++i) {
> >         go(f)
> >     }
> > ```
> 
> but does this guarantee to schedule on every scheduler once and only once?

Em..  It can't be guaranteed in multi-threading environment..

**Comment by DisableAsync** [comment]
im currently doing this:
the `int` is some kind of event id
the thing that stores all data:
```
thread_local std::map<sock_t, std::set<int>> t_updates;

// go_all(std::bind(dispatch_events, 42));
void dispatch_events(int i)
{
    for (auto&& [socket, updates] : t_updates)
        updates.insert(i);
}
```

in every coroutine that handles a socket connections: 
```
auto& updates = t_updates[&socket];
while (true)
{
    // other code
    for (auto&& i : updates)
        // do sth with i;
    updates.clear();
    // other code
}
```

any suggestion, for improvement?

**Comment by idealvin** [comment]
@DisableAsync 

It seems good enough. No better suggestion now..  Use `std::unordered_map` and `std::unordered_set` instead, maybe.

**Comment by DisableAsync** [comment]
ahh yes, hash tables are usually faster xD

but now i have an interesting question...
should i make the mapped type, the `std::unordered_set<int>` in this case, a pointer to the object instead of the object itself. in case the object gets moved away and invalidates the references and pointers to it. you know, in other containers like `std::vector`, when the container's size grows or shrinks, this happens a lot (?)

is this even a problem for red black trees and hash tables (i seriously dont have a clue about them, pardon me xD)

**Comment by idealvin** [comment]
> ahh yes, hash tables are usually faster xD
> 
> but now i have an interesting question...
> should i make the mapped type, the `std::unordered_set<int>` in this case, a pointer to the object instead of the object itself. in case the object gets moved away and invalidates the references and pointers to it. you know, in other containers like `std::vector`, when the container's size grows or shrinks, this happens a lot (?)
> 
> is this even a problem for red black trees and hash tables (i seriously dont have a clue about them, pardon me xD)

Use `std::map<sock_t, std::shard_ptr<std::set<int>>>`  instead then. It is always safe.

**Comment by DisableAsync** [comment]
i personally prefer raw pointers tho, just dont like the overhead smart pointers generate.

thanks for all the help, its been great. <3
