### ISSUE TITLE
error: src/thread.cc:93:18: error: use of undeclared identifier 'ETIMEDOUT'

### ISSUE THREAD

**Issue by cchbym** [idealvin/co#143]
MacOS:
      #include<errno.h>

**Comment by idealvin** [comment]
@

> MacOS:
> #include<errno.h>

@cchbym  Does `#include<errno.h>` solve this problem?

**Comment by cchbym** [comment]
> > MacOS:
> > #include<errno.h>
> 
> @cchbym Does `#include<errno.h>` solve this problem?

 yeah!

**Comment by cchbym** [comment]
problem has been solved
