### ISSUE TITLE
ssl & https support

### ISSUE THREAD

**Issue by idealvin** [idealvin/co#150]
Hi all,

I have added a support for ssl and https recently. I have not tested it widely. Someone helps?

- http & https server
  ```cpp
  http::Server s;
  s.on_req(...);                                     // set a callback to handle http request
  s.start("0.0.0.0", 80);                            // start as a http server
  s.start("0.0.0.0", 443, "privkey.pem", "ca.pem");  // start as a https server
  ```
- http & https client
  ```cpp
  http::Client c("http://github.com");   // http client to github.com:80
  http::Client c("https://github.com");  // https client to github.com:443
  http::Client c("127.0.0.1:7777");      // http client to  127.0.0.1:7777
  http::Client c("https://[::1]:443");   // https client to ipv6 ::1 with port 443
  c.get("/");
  ```
More details can be found in `co/so/ssl.h`, `src/so/ssl.cc`, `co/so/http.h`, `src/so/http.cc`.

**Comment by idealvin** [comment]
I'm not to maintain a large HTTP library by myself, as it is really complicated. 

The `http::Client` is finally implemented based on [libcurl](https://curl.se/libcurl/). 

I have to use multi handle of libcurl to make the http client work in coroutine environments. It is a little hard to understand. See documents below to get a better understanding of libcurl's multi handle.

[https://everything.curl.dev/libcurl/drive/multi-socket](https://everything.curl.dev/libcurl/drive/multi-socket)

For `http::Server`, I added a support for [Chunked Transfer-Encoding](https://www.jmarshall.com/easy/http/#http1.1s3). It's really complicated and stupid. He grandmother's. I'll add nothing for `http::Server` in the future.

**Comment by DisableAsync** [comment]
What about SSL error handling, I don't see them in the interfaces?

**Comment by idealvin** [comment]
> What about SSL error handling, I don't see them in the interfaces?
> 
> I mean something like certificate verification errors.

ssl::strerror(SSL*).

**Comment by DisableAsync** [comment]
> In co/so/ssl.h, there is a `ssl::strerror(SSL*)`

This thing is not so desirable, judging for its comment. =P

Back in April, when you first submitted this issue, i tried a very simple listen, connect, send and receive example, with a self signed certificate. there was no warning, no error. and there was no way to set verification depth either.

**Comment by idealvin** [comment]
> self signed certificate

@DisableAsync 

The error design in openssl is complicated. I'd better concentrate on the I/O operations with SSL in coroutine. If users want to handle certificate verification errors or something similar, they can just call raw APIs of openssl.

**Comment by idealvin** [comment]
Someone may send a pull request if he has a good solution. I have no time to find out how to handle those errors these days..
