### ISSUE TITLE
why use static library

### ISSUE THREAD

**Issue by j7252008** [idealvin/co#156]
一般都使用动态库，请问co优先使用静态库出于什么考虑呢

**Comment by idealvin** [comment]
co 本身支持动态库，修改 co/src/xmake.lua，将  `set_kind("static")`  修改为 `set_shared("shared")` 即可

**Comment by j7252008** [comment]
这个我只知道，我只是想问下这类基础库是不是使用静态库方式更好一点，还是说纯属个人爱好，求答疑

**Comment by idealvin** [comment]
主要是动态库的初始化会比较麻烦。co 中包含一些静态全局变量，使用动态库时，这些全局变量的初始化顺序很难理清..

**Comment by idealvin** [comment]
动态库中包含全局变量 x，程序 a 与程序 b 应该各有一份 x，互不影响，动态库可能是在运行时做了一次拷贝，这个要比静态库麻烦些。

**Comment by j7252008** [comment]
好的，多谢
