### ISSUE TITLE
创建协成使用go  会失败

### ISSUE THREAD

**Issue by huangjj852** [idealvin/co#158]
vs2019 x64在debug版本下   go一百万个协成正常 每个协成都会执行   但是改成release版本后同样的代码 只有七百多万协成执行了  其他的没有执行
代码就是demo中go里面 一个一百万循环 go([i]{ LOG << i;}); 
搞了好几天了 找不出问题

**Comment by idealvin** [comment]
> vs2019 x64在debug版本下 go一百万个协成正常 每个协成都会执行 但是改成release版本后同样的代码 只有七百多万协成执行了 其他的没有执行
> 代码就是demo中go里面 一个一百万循环 go([i]{ LOG << i;});
> 搞了好几天了 找不出问题

@huangjj852 
你是通过日志看有多少执行的吗？

**Comment by idealvin** [comment]
默认日志文件最大256m，最多8个，我猜你每条日志40字节左右，7百万时，刚好超过了一个日志文件的最大大小

**Comment by idealvin** [comment]
你看下二进制文件目录下的logs目录，里面可能有多个日志文件

**Comment by idealvin** [comment]
https://www.zhihu.com/pin/1382423873275715584

这里有群二维码，可以扫码进群，有问题及时反馈，以免浪费不必要的时间
