### ISSUE TITLE
Does CO support vcpkg?

### ISSUE THREAD

**Issue by Domacles** [idealvin/co#18]

**Comment by idealvin** [comment]
Someone may send a PR.

**Comment by hudengjunai** [comment]
strongly recommend  support vcpkg.

**Comment by idealvin** [comment]
> strongly recommend support vcpkg.

To be supported later.

**Comment by idealvin** [comment]
https://github.com/microsoft/vcpkg/pull/19535

**Comment by idealvin** [comment]
Vcpkg has merged the port, and now we can install co through vcpkg:
```
vcpkg install co:x64-windows

# HTTP & SSL support
vcpkg install co[libcurl,openssl]:x64-windows
```
