### ISSUE TITLE
windows下路径问题

### ISSUE THREAD

**Issue by 909254** [idealvin/co#180]
1、目前路径函数都是"/",而windows下路径默认是“\\”
更改如下
inline std::pair<fastring, fastring> split(const fastring& s) {
    size_t p = **s.rfind('\\');**
    if (p == s.npos) return std::make_pair(fastring(), s);
    return std::make_pair(s.substr(0, p + 1), s.substr(p + 1));
};
2、os::cwd() 路径获取有问题  有时候获取到的目录不正确，我进行了如下更改
fastring cwd() {
	char buf[264];
	DWORD r = GetModuleFileName(NULL, buf, sizeof(buf));
	fastring a;
	a = fastring(buf, r);
	fastring b = path::dir(a);
	return b;
}

**Comment by idealvin** [comment]
感谢反馈！

- `path` 是从 golang 移植过来的，windows '/' 与 '\' 都支持，设计的时候默认路径分隔符为 '/'，与 unix 保持一致。
- `os::cwd()` 在 windows 上用 `GetCurrentDirectory` 实现的，查了下官方文档，多线程可能不安全。可以提个 PR，但暂时不要用 `path::dir()` 实现。

**Comment by idealvin** [comment]
- `os::cwd()` 不一定是 module path
- path 统一用 `/`
- 要改的话，`os::cwd()` 在 windows 上，将返回结果中的 `\` 替换成 `/`，全部统一用 `/`
