### ISSUE TITLE
Event wait和signal建议增加个附加参数用于协程间消息传递

### ISSUE THREAD

**Issue by 909254** [idealvin/co#181]
用途：协程A :{
 wait( uint32 ms,int ExData)
COUT << ExData;
}
协程B:
{
ExData=123;
signal(int ExData)
}

**Comment by idealvin** [comment]
> 用途：协程A :{
> wait( uint32 ms,int ExData)
> COUT << ExData;
> }
> 协程B:
> {
> ExData=123;
> signal(int ExData)
> }

  这个要考虑下，目前 CO 采用的共享栈实现方式，直接通过栈上的数据传递消息不安全

**Comment by idealvin** [comment]
> 我现在简单实现了一下 增加了个整数成员 通过这个成员传递指针 ，由wait（）后释放， 这样只能wait超时-1或很大才行 不然会内存泄漏而且只能一对一。
> 还有个思路暂时没有去实现：增加个缓存类，这个类存储对象和超时时间，超时就释放掉，由缓存类负责回收。

协程间传递消息，可以用 `co::Chan`，类似于 golang 中的 channel。用 `co::Event` 传数据没那么容易设计，要考虑多对多的问题。

**Comment by idealvin** [comment]
https://www.zhihu.com/people/vin.cc

**Comment by 909254** [comment]
好的 私信你了
