### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [idealvin/co#19]
I would like to point out that identifiers like “[`_Log`](https://github.com/idealvin/co/blob/aa97cc0dd7e8314b2a0993fae7ec0da30e147dc1/base/log.h#L27 "Update candidate")” and “[`__STACKWALKER_H__`](https://github.com/idealvin/co/blob/aa97cc0dd7e8314b2a0993fae7ec0da30e147dc1/base/stack_trace/StackWalker.h#L1 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by idealvin** [comment]
fixed. thanks.

**Comment by elfring** [comment]
Thanks for [your small source code adjustment](https://github.com/idealvin/co/commit/0c449314e0fabe61f2dfe00d7b5cfe3bedf422cb "Renaming of a few identifiers").

[Were any update candidates left over](https://github.com/idealvin/co/blob/0c449314e0fabe61f2dfe00d7b5cfe3bedf422cb/base/log.cc#L22 "Update candidate")?

**Comment by idealvin** [comment]
Anything wrong with namespace ___ ?  No problem from my opinion.

**Comment by lhmouse** [comment]
[ISO/IEC WG21 N4835](https://github.com/cplusplus/draft/blob/master/papers/n4835.pdf):

> ## 5.10 Identifiers [lex.name]
> 3 In addition, some identifiers are reserved for use by C ++ implementations and shall not be used otherwise; no diagnostic is required.
> (3.1) — Each identifier that **contains a double underscore __** or **begins with an underscore followed by an uppercase letter** is reserved to the implementation for any use.
> (3.2) — Each identifier that **begins with an underscore** is reserved to the implementation for use as a name **in the global namespace**.
