### ISSUE TITLE
tcp::Server.exit()无法正确退出

### ISSUE THREAD

**Issue by aijle** [idealvin/co#193]
系统环境是macos，原因是accept没有收到唤醒，但是通过下面的方法成功退出了
`co::go([this]{`
 `     this->s.exit();`
  `});`
  `co::go([this]{`
  `   tcp::Client c("127.0.0.1", this->port, !this->key.empty());`
  `    c.connect(3000);`
  `});`
另外，http服务也缺少exit方法。

**Comment by idealvin** [comment]
@aijle 

更新一下代码试试，
`exit()` 不需要在协程中调用，没必要 `go([](){ s.exit(); })`

可以给我发个邮件，或在 [zhihu](https://www.zhihu.com/people/vin.cc) 上私信我，申请进群。

**Comment by idealvin** [comment]
@aijle 
在 mac 上试过了，最新的代码 exit() 是可以正常退出的
```cpp
xmake -b tcp
xmake r tcp
```

**Comment by aijle** [comment]
嗯，我用的是2.0.2分支。谢谢。
