### ISSUE TITLE
作为一个网络库怎么能没有定时器呢？

### ISSUE THREAD

**Issue by XLPE** [idealvin/co#2]
希望能补充定时器的功能

**Comment by idealvin** [comment]
co 中的 api 可以带一个超时时间的参数，不需要定时器

**Comment by XLPE** [comment]
比如在程序执行过程中可以定时或延期的触发一些任务，而不阻塞主任务

**Comment by idealvin** [comment]
线程库中有一个 TaskSched类，支持定时任务

**Comment by idealvin** [comment]
用协程写网络程序，一般不会出现你说的阻塞问题，协程库内部实现自动切换

**Comment by idealvin** [comment]
协程的基本用法:
不同的任务，创建不同的协程，一个协程io阻塞时，内部自动切换到其他协程

**Comment by XLPE** [comment]
TaskSched类的确是可以
