### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [idealvin/co#20]
I guess that a different program design will be needed for your function “[on_signal](https://github.com/idealvin/co/blob/0c449314e0fabe61f2dfe00d7b5cfe3bedf422cb/base/log.cc#L31 "Update candidate")".
I interpret the software situation in the way that the usage of the static variable “[logger](https://github.com/idealvin/co/blob/0c449314e0fabe61f2dfe00d7b5cfe3bedf422cb/base/log.cc#L265 "level_logger()")” might not fit to [async-signal-safety](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").

**Comment by lhmouse** [comment]
That signal thing is nonsense. The author has little knowledge about signal handlers, not exclusively there but also [here](https://github.com/idealvin/co/blob/0c449314e0fabe61f2dfe00d7b5cfe3bedf422cb/base/stack_trace/stack_trace_unix.cc#L136).

**Comment by idealvin** [comment]
It works well at present. Seems no need to worry about it.

**Comment by lhmouse** [comment]
> It works well at present. Seems no need to worry about it.

_It works_ is not a sufficient condition for _it is correct in principle_. If you call AS-unsafe functions in a signal handler then your code results in **undefined behavior**. Ignorance will not be tolerated.

**Comment by elfring** [comment]
[Were any update candidates left over](https://github.com/idealvin/co/blob/69b08796c3f48b2c8a5cdb8c04330dfb5cf3d647/base/stack_trace/stack_trace_win.cpp#L98 "Update candidate: StackTraceImpl::on_signal()")?

-----

Would you like to consider other software design options?
- [sigwaitinfo()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html)
- [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html)

**Comment by idealvin** [comment]
> [Were any update candidates left over](https://github.com/idealvin/co/blob/69b08796c3f48b2c8a5cdb8c04330dfb5cf3d647/base/stack_trace/stack_trace_win.cpp#L98)?
> 
> Would you like to consider other software design options?
> 
> * [sigwaitinfo()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html)
> * [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html)

Thanks for your suggestion. I'll consider about it.

**Comment by idealvin** [comment]
> [Were any update candidates left over](https://github.com/idealvin/co/blob/69b08796c3f48b2c8a5cdb8c04330dfb5cf3d647/base/stack_trace/stack_trace_win.cpp#L98)?
> 
> Would you like to consider other software design options?
> 
> * [sigwaitinfo()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html)
> * [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html)

@elfring 
The self-pipe trick is a good idea. Thanks again.

**Comment by idealvin** [comment]
@elfring 
The self-pipe trick seems working only on posix systems? Is there an aternative on windows?

**Comment by elfring** [comment]
Would you find the constraints for the application of the function “sigwaitinfo” more reasonable?

**Comment by idealvin** [comment]
> Would you find the constraints for the application of the function “sigwaitinfo” more reasonable?

I'm not familiar with it. I'll see more details about it later.

**Comment by elfring** [comment]
Will it matter for you if [signal notifications would be handled only by a separate thread](https://stackoverflow.com/questions/6223191/dealing-with-asynchronous-signals-in-multi-threaded-program "Dealing with asynchronous signals in multi-threaded program")?

**Comment by idealvin** [comment]
I think it's yes. I have to get the stack trace info in the crashed thread.



---Original---
