### ISSUE TITLE
关于定长整数类型

### ISSUE THREAD

**Issue by frederick-vs-ja** [idealvin/co#24]
本库引入了定长整数类型别名。但有一些处理让我觉得困惑：
- `fastring` 的内部引用计数类需要假定 
`unsigned int` 的长度；
- `Random` 的整个操作看起来需要依赖标准整数类型的长度；
- 以及可能存在的其他依赖标准整数类型长度的实现。

这些地方是不是直接使用定长整数类型别名更好？

其次，本库的定长整数类型依赖了 `<stdint.h>` 。它是 C99/C++11 起的标准库头文件，即使 MSVC 也支持。
是否考虑在此方面移除对 `_MSC_VER` 的检测？

**Comment by idealvin** [comment]
多是一些遗留问题，stdint.h好像是vs2013才支持的。可以提个PR清理下这些问题

**Comment by idealvin** [comment]
random 生成的是32位的随机数，另一个项目 [docs](https://github.com/idealvin/docs) 中有原理介绍。

**Comment by idealvin** [comment]
@frederick-vs-ja 
应该可以直接包含 stdint.h，现在不需要考虑老版本的vs.

- fastring   unsigned int  可以用 uin32 或 uint32_t 替换  
- Random 可以换成 uint32_t  uint64_t
