### ISSUE TITLE
fastring 的原位构造函数

### ISSUE THREAD

**Issue by frederick-vs-ja** [idealvin/co#25]
现版本的 `fastring` 拥有[直接利用未被管理的内存的构造函数](https://github.com/idealvin/co/blob/master/base/fastring.h#L45)。看起来此构造函数得到使用的地方看起来很少（目前只注意到[此处](https://github.com/idealvin/co/blob/master/base/fastream.h#L286)），而且写法上没有体现原位构造的特征。

我个人认为把它改成 static 成员函数（如 `fastring::from_raw_buffer` ）或者友元自由函数（如 `friend raw_buffer_to_fastring` ）会让用户更谨慎而安全地使用。

另外，或许只把此功能作为内部实现而非作为公开 API 也是一种选择。

**Comment by ice1000** [comment]
这个 issue 为什么在没有任何回复的情况下被关闭了……？

**Comment by tanpero** [comment]
**这﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿个﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿问﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿题﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿为﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿什﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿么﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿在﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿没﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿有﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿任﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿何﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿回﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿复﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿的﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿情﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿况﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿下﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿被﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿关﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿闭﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿了……？**

**Comment by tanpero** [comment]
这﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿个﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿问﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿题﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿为﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿什﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿么﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿在﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿没﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿有﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿任﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿何﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿回﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿复﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿的﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿情﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿况﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿下﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿被﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿关﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿闭﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿了……？
