### ISSUE TITLE
fastream/magicstream 与 fastring 的所有权问题

### ISSUE THREAD

**Issue by frederick-vs-ja** [idealvin/co#26]
相关问题： #25 

现版本中 `fastream` 底层并未使用 `fastring` 实现，而是使用了类似 C++ 标准的 `std::vector` 的实现，并且具有独占所有权语义。
另一方面，与之相关的 `magicstream` 存在所有权不明和另外的实现问题：

- `magicstream` 底层直接使用 `fastream` ，但是相当于把析构函数变成了 no-op ，潜在地有内存泄露。
- `magicstream` 提供把内容转交给 `fastring` 的函数。但流中有效内容是从缓冲区的首个字节开始的，并没有预留给引用计数的空间，这样会使得转换后得到的 `fastring` 丢失最前面的内容。
- `magicstream` 把内容转交给 `fastring` 后仍然保有对该缓冲区的所有权，而且不管理引用计数，这会使得释放缓冲区出现混乱。

我个人希望移除 `magicstream` 并将其功能整合到 `fastream` 中（这在 C++11 移动语义支持下是自然的）。目前有以下几类建议：

1.  `fastream` 本身为缓冲区预留引用计数的空间，一旦调用移动版本的 `str` ，则原位构造 `fastring` ，而流对象自身变为空状态（交出所有权）。
2. 另外提供一个拥有独占所有权语义的字符串类（类似 C++11 开始的 `std::basic_string` ），调用移动版本的 `str` 同样会交出所有权。
3. `fastream` 本身改用（独占或共享的）字符串类实现，提供取得和转交字符串类所管理的内存所有权的功能，避免额外的内存管理问题。

**Comment by idealvin** [comment]
magicstream 预留了 16 个字节，作为 fastring 的头部，设计上没有问题。

**Comment by idealvin** [comment]
设计 magicstream 是用来做下面的事情:
fastring s = (magicstream() << "hello" << 23).str();

**Comment by frederick-vs-ja** [comment]
了解。
目前我的理解是虽然底层用 `fastream` ，但 `magicstream` 对缓冲区中有效内容开始位置是不一致的。

**Comment by idealvin** [comment]
@frederick-vs-ja 
对的。

1. fastring 内部仅一个指针成员，指向一块连续的内存，内存前 16 个字节保存引用计数、容量、字符串长度。
2. magicstream 内部，利用 placement new 构造了一个 fastream 对象，这样可以避免调用 fastream 的析构函数。
3. fastream 内部分配了一块连续内存，为了将这块内存转换为 fastring 对象，需要预留首部 16 个字节。

仔细研究下 C++ 对象的内存布局。

**Comment by frederick-vs-ja** [comment]
@idealvin 
> 2. magicstream 内部，利用 placement new 构造了一个 fastream 对象，这样可以避免调用 fastream 的析构函数。

但是这里仍然存在潜在的泄漏问题（无法设计出一定让用户调用 `str` 的写法）。而且假如 `magicstream` 继续被使用，则它可能会使得转换得到的 `fastring` 对象变得非法。
个人认为比较好的处理是调用 `magcistream::str` 后， `magicstream` 交出所有权，自身改为管理一个新的缓冲区或在不管理缓冲区的空状态。而 `~magicstream` 维持析构功能以免内存泄漏。

不过就这些内容我仍有一些疑问：

1. 是否使 `magicstream` 拥有不管理缓冲区的空状态？个人觉得这是好的，但可能会使其他操作设计变得复杂。
2. 默认构造的 `fastream` 或 `magicstream` 是否在空状态为好？
3. 是否为流类加入立即释放缓冲区的 `reset` 方法？

**Comment by idealvin** [comment]
magicstream 之所以叫这个名字，就是因为里面涉及一些黑操作，当初也只是自己内部优化才用(str.cc, json.cc)，没打算给一般用户使用

**Comment by idealvin** [comment]
引入空状态，增加了额外判断的开销，代码也更为复杂，实际应用中，没有必要。
没有引入 reset，但可以用 swap 操作释放内存:
fastream s;
s.swap(fastream());

**Comment by lhmouse** [comment]
> 引入空状态，增加了额外判断的开销，代码也更为复杂，实际应用中，没有必要。
没有引入 reset，但可以用 swap 操作释放内存:
fastream s;
s.swap(fastream());

难道 [为了防止手贱而四处爆炸](https://github.com/lhmouse/asteria/blob/e2b04e344d350f7e02e6ddfe1fd1c2dc7a7388bc/asteria/rocket/cow_string.hpp#L400) 也是“没有必要”吗？

连应届生水平的设计规范都没有，还敢拿出来发布，真是冒天下之大不韪。
