### ISSUE TITLE
release下执行vs2015 logTest文件报错

### ISSUE THREAD

**Issue by UncleJuJu** [idealvin/co#28]
FLOG << "This is FLOG (fatal).. " << 23;
执行这句的时候报错
0x00007FFFD0CCE91E (ucrtbase.dll) (**.exe 中)处有未经处理的异常: 请求了严重的程序退出。
想问下是什么情况导致的？
代码和设置没有做任何更改

**Comment by idealvin** [comment]
FLOG 是 fatal 日志，打印 fatal 日志，会中止程序执行

**Comment by UncleJuJu** [comment]
好的谢谢，新人一枚，不是很懂 多谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Alvin"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月6日(星期五) 上午10:07
收件人:&nbsp;"idealvin/co"<co@noreply.github.com&gt;;
抄送:&nbsp;"atom豆花"<1037850292@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [idealvin/co] release下执行vs2015 logTest文件报错 (#28)




FLOG 是 fatal 日志，打印 fatal 日志，会中止程序执行

**Comment by lhmouse** [comment]
为什么不叫 `TERMINATE` ？
