### ISSUE TITLE
这作者根本就什么都不懂，大家散了吧

### ISSUE THREAD

**Issue by lhmouse** [idealvin/co#3]
1. [在头文件里定义虚拟函数](https://github.com/idealvin/co/blob/619b72a4bec01361505494597fbaf3e46c50fc29/base/rpc.h#L10) 不可取。
2. [signal handler](https://github.com/idealvin/co/blob/619b72a4bec01361505494597fbaf3e46c50fc29/base/stack_trace/stack_trace_unix.cc#L135) 不允许调用绝大多数标准库函数（包括内存管理）。
3. [coro 直接拿了其他人的没在外面带 license](https://github.com/idealvin/co/blob/master/base/co/context/context_arm64.S#L18)。
4. [`Random` 的默认构造器是 explicit 的](https://github.com/idealvin/co/blob/619b72a4bec01361505494597fbaf3e46c50fc29/base/random.h#L5) 而且 LCG 的质量很堪忧。没有公开的 spec。
5. 大量使用 `_Reserved` 等等保留标识符。
6. 完全没有考虑 **exception safety**，脑子里没概念。
7. [`swap()` 的形参应为左值引用](https://github.com/idealvin/co/blob/619b72a4bec01361505494597fbaf3e46c50fc29/base/json.h#L371)。
8. [头文件里不应实例化类模板](https://github.com/idealvin/co/blob/619b72a4bec01361505494597fbaf3e46c50fc29/base/json.h#L349)。
9. [JSON String 居然可以从 `void*` 构造](https://github.com/idealvin/co/blob/619b72a4bec01361505494597fbaf3e46c50fc29/base/json.h#L175)，但是 JSON 并不支持二进制数据。
10. [同样， JSON 也不支持 `int64`](https://github.com/idealvin/co/blob/619b72a4bec01361505494597fbaf3e46c50fc29/base/json.h#L212)。
11. [重载不带 SFINAE 的模板](https://github.com/idealvin/co/blob/619b72a4bec01361505494597fbaf3e46c50fc29/base/fastring.h#L162) 会在例如 `char*` 等不存在 exact match 的实参上造成歧义或错误匹配。
12. [`fastring` 居然没有 `compare()`](https://github.com/idealvin/co/blob/619b72a4bec01361505494597fbaf3e46c50fc29/base/fastring.h#L353) 函数。

就看了这么多，其它的懒得看了。基本没有完全不存在问题的文件。作者不仅 C++ 语言本身功底薄弱，而且对操作系统、设计法则等了解也不够深入。

**Comment by FrankHB** [comment]
我橘得不需要浪费 issue number，该 reopen 一下。

https://github.com/idealvin/co/blob/master/readme.md

> `CO` 是一个优雅、高效的 C++ 基础库，支持 Linux, Windows 与 Mac 平台。  

排除主观的自卖自夸，光看用了 reserved identifier 导致 UB 就让这个“支持”变成扯蛋：恁是打算直接代替厂商撸内核呢，还是提供自主研发的 toolchain 来“支持”呢？疑惑是跟主流厂商有 py 交易能把支持外包过去？

**Comment by lhmouse** [comment]
建议上某乎挂一番（
