### ISSUE TITLE
base xmake错误：ambiguating new declaration of ‘__pid_t xxGettid()’

### ISSUE THREAD

**Issue by codehz** [idealvin/co#32]
```
error: co/impl/../../unix/thread.h:184:16: 错误：ambiguating new declaration of ‘__pid_t xxGettid()’
  184 | #define gettid xxGettid
      |                ^~~~~~~~
co/impl/../../unix/thread.h:178:21: 附注：old declaration ‘unsigned int xxGettid()’
  178 | inline unsigned int xxGettid() {
      |                     ^~~~~~~~
```

**Comment by codehz** [comment]
__pid_t 似乎是int
但是为什么编译器会检查宏定义呢
使用的是g++ 9.2.0

**Comment by codehz** [comment]
原来是这样的，
后面有一个头文件
/usr/include/bits/unistd_ext.h
（被unistd.h包含）其中有一句
extern __pid_t gettid (void) __THROW;
看起来是因为宏替换的缘故导致这个定义也被替换了，然后自然就报错了

**Comment by codehz** [comment]
一个解决方案是提前包含unistd.h然后让它不会互相影响。。。
就是在thread.h开头先包含unistd.h

**Comment by idealvin** [comment]
> 一个解决方案是提前包含unistd.h然后让它不会互相影响。。。
> 就是在thread.h开头先包含unistd.h

嗯，之前了解到，glibc 2.30 加入了 gettid，但头文件是 <sys/types.h>，所以 thread.h 提前包含了。
@codehz  可以提交一个 pull requrest 吗？ 确保你那边编译通过

**Comment by idealvin** [comment]
文档中特别有说明，可以参考[这里](https://github.com/idealvin/co/blob/master/docs/cn/14.%E7%BA%BF%E7%A8%8B%E5%BA%93(thread).md#144-%E8%8E%B7%E5%8F%96%E5%BD%93%E5%89%8D%E7%BA%BF%E7%A8%8B%E7%9A%84-id)

**Comment by idealvin** [comment]
@codehz 我这里暂时没有 g++ 9.2 的编译环境，请帮忙在编译通过的情况下，提交一个 PR，修复此问题，谢谢

**Comment by idealvin** [comment]
thread.h 修改一下：

**Comment by codehz** [comment]
@idealvin 已经发了

**Comment by idealvin** [comment]
> @idealvin 已经发了

好的，非常感谢。glibc 提供的 gettid() 可能只是简单包装了系统调用，效率低，还是引入 TLS 机制比较合适。

**Comment by codehz** [comment]
@idealvin 我觉得最好的解决方法还是把这个重名函数给deprecated掉，然后换个别的不容易冲突的名字（最后某个版本再删除这个名字）。因为没法控制别的地方也来一个extern声明。。。

**Comment by idealvin** [comment]
> @idealvin 我觉得最好的解决方法还是把这个重名函数给deprecated掉，然后换个别的不容易冲突的名字（最后某个版本再删除这个名字）。因为没法控制别的地方也来一个extern声明。。。

嗯，对的，后面会考虑重命名

**Comment by idealvin** [comment]
> @idealvin 我觉得最好的解决方法还是把这个重名函数给deprecated掉，然后换个别的不容易冲突的名字（最后某个版本再删除这个名字）。因为没法控制别的地方也来一个extern声明。。。

已经将 gettid 重命名为 current_thread_id，相当于恢复到了最初的设定.
