### ISSUE TITLE
将co log编入dll，产生.fatal

### ISSUE THREAD

**Issue by CNchence** [idealvin/co#35]
将co log编入dll，使用c#调用，.log文件中会缺失很多条log，并且会产生.fatal文件，.fatal文件事例如下：

1216 22:30:33] Error: Unrecognized Exception
D:\Project\co\base\stack_trace\StackWalker.cpp (1096): StackWalker::ShowCallstack
D:\Project\co\base\stack_trace\stack_trace_win.cpp (203): `anonymous namespace'::StackTraceImpl::on_exception
00007FFBA96B78D8 (ntdll): (filename not available): RtlInitializeCriticalSection
00007FFBA965D4FA (ntdll): (filename not available): RtlWalkFrameChain
00007FFBA965BE9A (ntdll): (filename not available): RtlRaiseException
00007FFBA671A388 (KERNELBASE): (filename not available): RaiseException
00007FFB54122413 (mono-2.0-bdwgc): (filename not available): mono_native_thread_set_name
00007FFB541D3B60 (mono-2.0-bdwgc): (filename not available): mono_thread_set_manage_callback
00007FFB541DC685 (mono-2.0-bdwgc): (filename not available): mono_threads_set_shutting_down
00007FFB541D57E8 (mono-2.0-bdwgc): (filename not available): mono_threads_set_shutting_down
00007FFB541D5576 (mono-2.0-bdwgc): (filename not available): mono_threads_set_shutting_down
00007FFBA8134034 (KERNEL32): (filename not available): BaseThreadInitThunk
00007FFBA96C3691 (ntdll): (filename not available): RtlUserThreadStart

1216 22:30:33] Error: Unrecognized Exception
D:\Project\co\base\stack_trace\StackWalker.cpp (1096): StackWalker::ShowCallstack
D:\Project\co\base\stack_trace\stack_trace_win.cpp (203): `anonymous namespace'::StackTraceImpl::on_exception
00007FFBA96B78D8 (ntdll): (filename not available): RtlInitializeCriticalSection
00007FFBA965D4FA (ntdll): (filename not available): RtlWalkFrameChain
00007FFBA965BE9A (ntdll): (filename not available): RtlRaiseException
00007FFBA671A388 (KERNELBASE): (filename not available): RaiseException
00007FFB54122413 (mono-2.0-bdwgc): (filename not available): mono_native_thread_set_name
00007FFB541D3B60 (mono-2.0-bdwgc): (filename not available): mono_thread_set_manage_callback
00007FFB541D8B0B (mono-2.0-bdwgc): (filename not available): mono_threads_set_shutting_down
00007FFB541DB231 (mono-2.0-bdwgc): (filename not available): mono_threads_set_shutting_down
00007FFB541D57E8 (mono-2.0-bdwgc): (filename not available): mono_threads_set_shutting_down
00007FFB541D5576 (mono-2.0-bdwgc): (filename not available): mono_threads_set_shutting_down
00007FFBA8134034 (KERNEL32): (filename not available): BaseThreadInitThunk
00007FFBA96C3691 (ntdll): (filename not available): RtlUserThreadStart

**Comment by idealvin** [comment]
请附上更加详细的问题描述
- 编译方法
- 问题代码

**Comment by idealvin** [comment]
@CNchence  从fatal 日志看，应该是mono 库里的异常，检查一下是不是用错了。

mono_native_thread_set_name
00007FFB541D3B60 (mono-2.0-bdwgc): (filename not available): mono_thread_set_manage_callback
00007FFB541D8B0B (mono-2.0-bdwgc): (filename not available): mono_threads_set_shutting_down
00007FFB541DB231 (mono-2.0-bdwgc): (filename not available): mono_threads_set_shutting_down
00007FFB541D57E8 (mono-2.0-bdwgc): (filename not available): mono_threads_set_shutting_down
00007FFB541D5576 (mono-2.0-bdwgc): (filename not available): mono_threads_set_shutting_down

**Comment by idealvin** [comment]
@CNchence

**Comment by idealvin** [comment]
@CNchence 
猜测 mono_native_thread_set_name 内部做了类似下面的事情，请参考[这里](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-set-a-thread-name-in-native-code?view=vs-2019)
```cpp
#pragma pack(pop)
void SetThreadName(DWORD dwThreadID, const char* threadName) {
    THREADNAME_INFO info;
    info.dwType = 0x1000;
    info.szName = threadName;
    info.dwThreadID = dwThreadID;
    info.dwFlags = 0;
#pragma warning(push)
#pragma warning(disable: 6320 6322)
    __try{
        RaiseException(MS_VC_EXCEPTION, 0, sizeof(info) / sizeof(ULONG_PTR), (ULONG_PTR*)&info);
    }
    __except (EXCEPTION_EXECUTE_HANDLER){
    }
#pragma warning(pop)
``

内部调用 RaiseException 抛出了异常，被 log 库捕捉到了。

用下面这段代码，复现了你的问题:
```cpp
//
// Usage: SetThreadName ((DWORD)-1, "MainThread");
//
#include <windows.h>
const DWORD MS_VC_EXCEPTION = 0x406D1388;
#pragma pack(push,8)
typedef struct tagTHREADNAME_INFO
{
    DWORD dwType; // Must be 0x1000.
    LPCSTR szName; // Pointer to name (in user addr space).
    DWORD dwThreadID; // Thread ID (-1=caller thread).
    DWORD dwFlags; // Reserved for future use, must be zero.
} THREADNAME_INFO;
#pragma pack(pop)
void SetThreadName(DWORD dwThreadID, const char* threadName) {
    THREADNAME_INFO info;
    info.dwType = 0x1000;
    info.szName = threadName;
    info.dwThreadID = dwThreadID;
    info.dwFlags = 0;
#pragma warning(push)
#pragma warning(disable: 6320 6322)
    __try{
        RaiseException(MS_VC_EXCEPTION, 0, sizeof(info) / sizeof(ULONG_PTR), (ULONG_PTR*)&info);
    }
    __except (EXCEPTION_EXECUTE_HANDLER){
    }
#pragma warning(pop)
}
```

**Comment by CNchence** [comment]
@idealvin 
感谢回答和分析，我在dll工程中Release运行目标exe，打印log正常，但是直接运行目标exe就会出现.fatal文件。看fatal文件的错误，怀疑是直接运行exe时log无法拿到目标线程名导致的错误。

**Comment by idealvin** [comment]
co/base/stack_trace/stack_trace_win.cpp
可以在[这个地方](https://github.com/idealvin/co/blob/7e40721455516cc627edc81cf89a764cd4c0246f/base/stack_trace/stack_trace_win.cpp#L193) 加一行 
```cpp
return 0;
```
忽略掉异常

**Comment by idealvin** [comment]
@CNchence 你按上面说的，忽略掉异常试试，应该不影响的

**Comment by idealvin** [comment]
@CNchence 有空请帮忙验证一下

**Comment by CNchence** [comment]
仍然会有问题，相应线程调用log打印的数据仍然无法写入文件

**Comment by idealvin** [comment]
base/log.h
extern __thread fastream* xxLog;
动态库中使用 __thread 可能有问题，你可以自行替换成 thread_ptr  验证一下，晚点再跟踪

**Comment by idealvin** [comment]
@CNchence 无法写日志到文件是另外一个问题，log 库捕获到异常后，调用 log::close() 关闭了写日志的线程。请更新代码，再验证一下

**Comment by idealvin** [comment]
我想已经修复了这个问题，请帮忙用最新的代码验证一下



idealvin@qq.com
 
发件人： CNchence
发送时间： 2019-12-17 20:26
收件人： idealvin/co
抄送： Alvin; State change
主题： Re: [idealvin/co] 将co log编入dll，产生.fatal (#35)
仍然会有问题，相应线程调用log打印的数据仍然无法写入文件

**Comment by CNchence** [comment]
新代码验证了，没有问题

**Comment by idealvin** [comment]
👌
