### ISSUE TITLE
Question about set_cloexec

### ISSUE THREAD

**Issue by wanggujin** [idealvin/co#37]
inline void set_cloexec(sock_t fd) {
    fcntl(fd, F_SETFL, fcntl(fd, F_GETFL) | O_EXCL);
}

`O_EXCL` or `FD_CLOEXEC` ?

**Comment by idealvin** [comment]
Perhaps I made a mistake. You may send a PR to fix it. Thanks.

**Comment by idealvin** [comment]
Sorry, I made a mistake here. Fixed as follow:
```cpp
inline void set_nonblock(sock_t fd) {
    fcntl(fd, F_SETFL, fcntl(fd, F_GETFL) | O_NONBLOCK);
}

inline void set_cloexec(sock_t fd) {
    fcntl(fd, F_SETFD, fcntl(fd, F_GETFD) | FD_CLOEXEC);
}
```
