### ISSUE TITLE
JSON实现不符合ECMA-404

### ISSUE THREAD

**Issue by zuoxinyu** [idealvin/co#4]
string没有实现`\uxxxx`形式的unicode转义，以及`\b` `\f`的转义。

看实现实在没法看出来为什么会比`rapidJSON`性能高，而`rapidJSON`甚至都用上了SIMD优化，麻烦给出benchmark？

**Comment by idealvin** [comment]
co/test 目录下有些测试代码，可按下面的步骤编译测试：  
```sh
cd co/base
scons -j4

cd co/test
./_build.sh rapidjson_test.cc
./_build.sh json_test.cc

cd ../build
./rapidjson.exe
./json.exe
```
如果编译有问题，请参考 pdf 文档

**Comment by idealvin** [comment]
上面只是一个简单的测试，完整的 benchmark 没时间弄，设计之初也只要求做到简单够用，并没打算支持完整的 json 标准

**Comment by idealvin** [comment]
有改进意见可以提 PR

**Comment by zuoxinyu** [comment]
> 上面只是一个简单的测试，完整的 benchmark 没时间弄，设计之初也只要求做到简单够用，并没打算支持完整的 json 标准

`\b`、`\f`还好，但是`\u`不转义的话根本不能称之为可用吧。如果嫌麻烦完全可以用第三方的JSON库~

**Comment by lhmouse** [comment]
JSON 还有  ‘\/` 这种玩意。另外，必须要求完整的 UCS-2 （强调一下 JSON  的语法不支持 UTF-32，也没限制一定用 UTF-16 ）。不支持 `\u` 基本和第三方返回带中文的 JSON 就再见了。

**Comment by lhmouse** [comment]
看了一下解析：
1. `int64` 溢出没有检测（事实上应该全部用 `double`），按下不表；
2. `str::to_double()` 是调用  `std::strtod()` 有全局 locale 的破事（法语俄语里的小数点是逗号），也不表；
3. 最严重的问题是 naive recursive descent  parser 可能导致栈溢出。对于 JSON 这种简单的文法其实个人感觉写个不递归的 LL(1) 才是相对安全的解决方案。

**Comment by zuoxinyu** [comment]
recursive decent其实还好……能通过[这里](http://www.json.org/JSON_checker/test.zip)的test case就够了。

**Comment by idealvin** [comment]
@zuoxinyu 可否提一个 PR?

**Comment by lhmouse** [comment]
> recursive decent其实还好……能通过这里的test case就够了。

哈哈拿 **Asteria** 跑了一下，跑出一堆 XPASS 出来。这里有几个 JSON5 的特性，但是都 Asteria 当扩展了。

**Comment by idealvin** [comment]
@zuoxinyu 已支持 \b \f \/  （支持这些几乎用不到的东西，性能会稍有下降)

\u 的支持，直接从 [jsoncpp](https://github.com/open-source-parsers/jsoncpp) 移植过来的

另外还有些像  1e7  的整数还不支持，谁有空可以提交个 patch 修正一下。
