### ISSUE TITLE
random.h中的一些疑惑

### ISSUE THREAD

**Issue by TpClark** [idealvin/co#42]
`uint32_t next() {`
`        static const uint32_t M = 2147483647L;  // 2^31-1`
 `       static const uint64_t A = 16385;  // 2^14+1`

  `      // Computing _seed * A % M.`
  `        uint64_t p = _seed * A;`
  `      _seed = static_cast<uint32_t>((p >> 31) + (p & M));`
  `      if (_seed > M) _seed -= M;`

   `     return _seed;`
  `  }`

其中if (_seed > M) _seed -= M; 这行是不是多余的， 因为M本来就是uint32_t的最大值， 上面一行强转uint32_t之后不能大于M， if这条语句是不可能走到的

**Comment by idealvin** [comment]
> `uint32_t next() {`
> ` static const uint32_t M = 2147483647L; // 2^31-1`
> ` static const uint64_t A = 16385; // 2^14+1`
> 
> ` // Computing _seed * A % M.`
> ` uint64_t p = _seed * A;`
> ` _seed = static_cast<uint32_t>((p >> 31) + (p & M));`
> ` if (_seed > M) _seed -= M;`
> 
> ` return _seed;`
> ` }`
> 
> 其中if (_seed > M) _seed -= M; 这行是不是多余的， 因为M本来就是uint32_t的最大值， 上面一行强转uint32_t之后不能大于M， if这条语句是不可能走到的

M不是 uint32最大值，最大是2^32-1
