### ISSUE TITLE
unitest xmake错误：error: unknown target(base) for unitest.deps!

### ISSUE THREAD

**Issue by ylsislove** [idealvin/co#46]
我根据文档上的xmake编译步骤，编译co/unitest时报错
`checking for the architecture ... x64`
`checking for the Microsoft Visual Studio (x64) version ... 2017`
`error: unknown target(base) for unitest.deps!`
该如何解决

**Comment by waruqi** [comment]
> 我根据文档上的xmake编译步骤，编译co/unitest时报错

请描述下你的执行步骤

**Comment by ylsislove** [comment]
`cd .\base\`
`xmake`
编译co/base 库的时候没有问题，但是会报一个警告，如下:
`warning: You are working in the project directory(E:\_Code\GitHub\co) and you can also
force to build in current directory via run xmake -P .`
但是在lib目录下成功生成了base.lib文件
然后按照步骤编译co/unitest
`cd ..\unitest\base\`
`xmake`
这里同样会报警告，按照它的提示运行
`xmake -P .`
然后就报错了
`checking for the architecture ... x64`
`checking for the Microsoft Visual Studio (x64) version ... 2017`
`error: unknown target(base) for unitest.deps!`

**Comment by idealvin** [comment]
> `cd .\base\`
> `xmake`
> 编译co/base 库的时候没有问题，但是会报一个警告，如下:
> `warning: You are working in the project directory(E:\_Code\GitHub\co) and you can also force to build in current directory via run xmake -P .`
> 但是在lib目录下成功生成了base.lib文件
> 然后按照步骤编译co/unitest
> `cd ..\unitest\base\`
> `xmake`
> 这里同样会报警告，按照它的提示运行
> `xmake -P .`
> 然后就报错了
> `checking for the architecture ... x64`
> `checking for the Microsoft Visual Studio (x64) version ... 2017`
> `error: unknown target(base) for unitest.deps!`

@ylsislove 
现在不需要 cd 到 base 目录，直接在 co 根目录编译，刚更新文档，请参考最新的文档说明

**Comment by waruqi** [comment]
嗯 之前更新了xmake.lua 所有命令都只需要在项目根目录完成

你试试执行 xmake build unitest 开构建

**Comment by idealvin** [comment]
估计现在混乱了，先 rm -rf 所有 .xmake 目录吧

**Comment by idealvin** [comment]
@ylsislove 
请参考最新的 md 文档或者 readme，pdf 好久没更新了，因为没有方便的自动生成右侧标签的方法

**Comment by waruqi** [comment]
> 估计现在混乱了，先 rm -rf 所有 .xmake 目录吧

之前那种方式 每个子目录都会有 .xmake 所以还是放到根目录统一执行 就不会污染项目目录 到处生成 build .xmake目录

不过现在新的方式，之前子目录下已有的.xmake并不影响现有的构建的，只是多了些冗余目录 删了也好 干净点

不过现在.gitignore里面我已经忽略了 可以执行 git clean -fd 清理下就好

**Comment by ylsislove** [comment]
依照最新文档，已经可以顺利编译通过了。但现在还有两个问题：
1、在测试`xmake run stack`、`xmake run stack -t`、`xmake run stack -m`这三个命令时会报错，报错如下
`Error: EXCEPTION_ACCESS_VIOLATION`
`e:\_code\github\co\base\stack_trace\stackwalker.cpp (1074): StackWalker::ShowCallstack`
`e:\_code\github\co\base\stack_trace\stack_trace_win.cpp (203): anonymous namespace'::StackTraceImpl::on_exception`
`00007FFE0CE38636 (ntdll): (filename not available): RtlIsGenericTableEmpty`
`00007FFE0CE2A0D6 (ntdll): (filename not available): RtlRaiseException`
`00007FFE0CE5FE6E (ntdll): (filename not available): KiUserExceptionDispatcher`
`e:\_code\github\co\test\stack_test.cc (15): a`
`e:\_code\github\co\base\co\impl\scheduler.cc (39): co::main_func`
`00007FF6904BDA10 (stack): (filename not available): tb_context_make`
`00007FF6904A9FDF (stack): (filename not available): co::Scheduler::loop_in_thread`
2、`cd co/base && ./_inc.sh   # 生成 co/inc 目录`这条命令，在windows下要生成头文件目录的话应该运行哪个文件

**Comment by idealvin** [comment]
这是对的，stack就是用于测试异常情况下打印函数堆栈信息的



---原始邮件---
发件人: "Yain"<notifications@github.com&gt;
发送时间: 2020年1月8日(周三) 晚上7:25
收件人: "idealvin/co"<co@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Alvin"<idealvin@qq.com&gt;;
主题: Re: [idealvin/co] unitest xmake错误：error: unknown target(base) for unitest.deps! (#46)



依照最新文档，已经可以顺利编译通过了。但现在还有两个问题：
 1、在测试xmake run stack、xmake run stack -t、xmake run stack -m这三个命令时会报错，报错如下
 Error: EXCEPTION_ACCESS_VIOLATION
 e:\_code\github\co\base\stack_trace\stackwalker.cpp (1074): StackWalker::ShowCallstack
 e:\_code\github\co\base\stack_trace\stack_trace_win.cpp (203): anonymous namespace'::StackTraceImpl::on_exception
 00007FFE0CE38636 (ntdll): (filename not available): RtlIsGenericTableEmpty
 00007FFE0CE2A0D6 (ntdll): (filename not available): RtlRaiseException
 00007FFE0CE5FE6E (ntdll): (filename not available): KiUserExceptionDispatcher
 e:\_code\github\co\test\stack_test.cc (15): a
 e:\_code\github\co\base\co\impl\scheduler.cc (39): co::main_func
 00007FF6904BDA10 (stack): (filename not available): tb_context_make
 00007FF6904A9FDF (stack): (filename not available): co::Scheduler::loop_in_thread
 2、cd co/base &amp;&amp; ./_inc.sh   # 生成 co/inc 目录这条命令，在windows下要生成头文件目录的话应该运行哪个文件

**Comment by idealvin** [comment]
呃，windows暂不支持..



---原始邮件---
发件人: "Yain"<notifications@github.com&gt;
发送时间: 2020年1月8日(周三) 晚上7:25
收件人: "idealvin/co"<co@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Alvin"<idealvin@qq.com&gt;;
主题: Re: [idealvin/co] unitest xmake错误：error: unknown target(base) for unitest.deps! (#46)



依照最新文档，已经可以顺利编译通过了。但现在还有两个问题：
 1、在测试xmake run stack、xmake run stack -t、xmake run stack -m这三个命令时会报错，报错如下
 Error: EXCEPTION_ACCESS_VIOLATION
 e:\_code\github\co\base\stack_trace\stackwalker.cpp (1074): StackWalker::ShowCallstack
 e:\_code\github\co\base\stack_trace\stack_trace_win.cpp (203): anonymous namespace'::StackTraceImpl::on_exception
 00007FFE0CE38636 (ntdll): (filename not available): RtlIsGenericTableEmpty
 00007FFE0CE2A0D6 (ntdll): (filename not available): RtlRaiseException
 00007FFE0CE5FE6E (ntdll): (filename not available): KiUserExceptionDispatcher
 e:\_code\github\co\test\stack_test.cc (15): a
 e:\_code\github\co\base\co\impl\scheduler.cc (39): co::main_func
 00007FF6904BDA10 (stack): (filename not available): tb_context_make
 00007FF6904A9FDF (stack): (filename not available): co::Scheduler::loop_in_thread
 2、cd co/base &amp;&amp; ./_inc.sh   # 生成 co/inc 目录这条命令，在windows下要生成头文件目录的话应该运行哪个文件

**Comment by waruqi** [comment]
这块头文件的提取安装也可以通过add_headerfiles 在xmake.lua里面处理，通过xmake install 或者 xmake packages 提取到对应安装目录或者build目录

**Comment by ylsislove** [comment]
已经没有问题了，感谢你们的帮助👍

**Comment by idealvin** [comment]
@ylsislove 
> 2、`cd co/base && ./_inc.sh # 生成 co/inc 目录`这条命令，在windows下要生成头文件目录的话应该运行哪个文件

新增了 xmake install 支持，执行 `xmake install -o pkg` 即可将头文件、库打包到 pkg 目录

**Comment by waruqi** [comment]
> @ylsislove
> 
> > 2、`cd co/base && ./_inc.sh # 生成 co/inc 目录`这条命令，在windows下要生成头文件目录的话应该运行哪个文件
> 
> 新增了 xmake install 支持，执行 `xmake install -o pkg` 即可将头文件、库打包到 pkg 目录

可以通过set_installdir 对每个target设置默认的安装目录到pkg下 也就不需要指定-o pkg参数了，直接执行xmake install 就行


https://xmake.io/#/zh-cn/manual/project_target?id=targetset_installdir

**Comment by idealvin** [comment]
@waruqi 
👌  马上加上

**Comment by idealvin** [comment]
@waruqi 
遇到一个问题，全局设置了 set_install，执行 xmake install -o 到其他目录无效

**Comment by waruqi** [comment]
> @waruqi
> 遇到一个问题，全局设置了 set_installdir，执行 xmake install -o 到其他目录无效

嗯 目前默认优先用了xmake.lua里面的设置，回头我调整下这块的优先级 你可以提个issues备着 回头我改进下
