### ISSUE TITLE
`json::Value::str()`不能正确地序列化某些浮点数值

### ISSUE THREAD

**Issue by tigerlee** [idealvin/co#48]
当JSON字符串中含有`1.0`之类的数值时，`json::Value::str()`会将其序列化为`1`，这与原来该字段的类型不符，如果多次依次执行序列化、反序列化操作，会导致断言。

版本：Commit 95535b3 之前都有此现象
系统：Debian 10（Windows未测试)
内核：5.4.0-1-amd64

示例
```c++
#include <stdio.h>

#include "base/json.h"

fastring s = "{\"value\": 12.0}";

int main(int argc, char** argv) {
    auto j1 = json::parse(s);
    auto j2 = json::parse(j1.str());

    printf("j1 value: %f\n", j1["value"].get_double());
    printf("j2 value: %f\n", j2["value"].get_double());

    return 0;
}
```

执行结果
```bash
j1[0]: 12.000000
j_test: ./base/json.h:226: double json::Value::get_double() const: Assertion `this->is_double()' failed.
error: execv(/home/tiger/Codes/co/build/linux/x86_64/release/j_test) failed(-1)!
```

原因：序列化操作使用了[`fast::dtoa()`](https://github.com/idealvin/co/blob/d44029f/base/fast.cc#L219)，而`fast::dtoa()`在输出浮点时使用了Conversion Specifier `g`，这会导致尾部的`0`会被移除。这样就造成了类型不一致的问题。

**Comment by idealvin** [comment]
@tigerlee 嗯，感谢反馈，确实是个问题，g 改成其他的格式能解决吗？

**Comment by idealvin** [comment]
@tigerlee 

早期实现 fast::dtoa() 时，主要用于在日志中打印符点数。

现在 fast::dtoa() 里加了个判断，结果不包含小数点的，自动在末尾加上 ".0"

**Comment by idealvin** [comment]
更新了一下，考虑到类似 2e-8 的符点数的存在，仅在不含 ".eE" 时，自动加上 ".0"
