### ISSUE TITLE
关于Json::Value::operator[]的疑问

### ISSUE THREAD

**Issue by tigerlee** [idealvin/co#49]
https://github.com/idealvin/co/blob/110eadde2c89dffa259a161c100cd4161253441f/base/json.cc#L15

正常访问一个`object`的`member`时，应该先调用`has_member()`来进行判断。但看上面函数的代码，如果直接使用`[]`来访问相关`member`，这里的逻辑似乎是打算支持这种行为？

如果不支持的话，21&22行的意义何在呢？
如果支持的话，接下来访问其它`member`或者调用`str()`就会出错了。如以下代码：

```c++
#include "co/json.h"

int main() {
  auto v = json::parse("{\"name\": \"tiger\"}");
  v["n"];
  printf("%s\n", v["name"].str().c_str());
  return 0;
}
```
输出结果是`null`

**Comment by idealvin** [comment]
@tigerlee 
json::parse() 传入错误的字符串，v 整个就是null，[]操作key不存在时，自动添加，你那个测试结果是正常的

**Comment by tigerlee** [comment]
> @tigerlee
> json::parse() 传入错误的字符串，v 整个就是null，[]操作key不存在时，自动添加，你那个测试结果是正常的

这样的允许用户犯错，但犯错的代价有点大啊。我因为这个问题单步调试找了一晚上。:cry:
有没有可能考虑这种方案：定义一个全局的空值，当输入有错时，返回这个空值的引用，不影响原来的Value？这样至少不会影响上面例子中第6行的执行。

**Comment by yanlinlin82** [comment]
@tigerlee 我倒是觉得现在的逻辑更合理些，也与STL中map（自动添加）的做法一致。返回全局空值，似乎可能造成更多混乱。真要限制自动添加，或许可考虑用const修饰一下？

**Comment by tigerlee** [comment]
> @tigerlee 我倒是觉得现在的逻辑更合理些，也与STL中map（自动添加）的做法一致。返回全局空值，似乎可能造成更多混乱。真要限制自动添加，或许可考虑用const修饰一下？

可是`map`的`operator[]()`在添加之后，不会影响到其它值呀。我举的例子中，不仅`v["name"]`值为`null`了，就连`v`本身也变成`null`了。我觉得这个影响有点大。

**Comment by yanlinlin82** [comment]
理解你的意思了，确实影响比较大。我觉得，这主要还是因为，相比std::map，json更像是个弱类型吧。

我以前也曾经实现过类似的json类，当时曾把这个问题视作一个feature，帮助快速构造复杂的json：

```cpp
json j;
j["a"]["b"]["c"] = 1;  // {"a":{"b":{"c":1}}}
```

如今看来，这的确很容易造成误解。

或许可以参考std::variant（<https://en.cppreference.com/w/cpp/utility/variant/get>），在发生类型变化（如null => object）时抛出异常？

**Comment by idealvin** [comment]
> https://github.com/idealvin/co/blob/110eadde2c89dffa259a161c100cd4161253441f/base/json.cc#L15
> 
> 正常访问一个`object`的`member`时，应该先调用`has_member()`来进行判断。但看上面函数的代码，如果直接使用`[]`来访问相关`member`，这里的逻辑似乎是打算支持这种行为？
> 
> 如果不支持的话，21&22行的意义何在呢？
> 如果支持的话，接下来访问其它`member`或者调用`str()`就会出错了。如以下代码：
> 
> ```c++
> #include "co/json.h"
> 
> int main() {
>   auto v = json::parse("{\"name\": \"tiger\"}");
>   v["n"];
>   printf("%s\n", v["name"].str().c_str());
>   return 0;
> }
> ```
> 
> 输出结果是`null`

@tigerlee 
上午你输入的 json 字符串有误，才会输出结果为 null。
你修正字符串后，不会输出 null，而是正常的 "tiger"。
请仔细检查下，应该不存在你描述的问题。

**Comment by tigerlee** [comment]
不好意思，在构建最小代码时没注意检查。以下是经检查后的代码：

```c++
#include "co/json.h"

int main() {
  auto v=json::parse("[{\"1\":1,\"2\":2,\"3\":3,\"4\":4,\"5\":5,\"6\":6,\"7\":7}]");
  Json i = v[0];
  i["8"];
  printf("%s\n", i.str().c_str());
  printf("%s\n", v[0].str().c_str());
  printf("%s\n", v.str().c_str());
  return 0;
}
```

这个问题的特殊点在于`object`的属性必须为7个(更多的我没试过，估计与内存分配算法有关)。
在第7行输出`i.str()`时是正常的，但后面的代码就不正常了。以上代码的输出结果如下：

```
{"1":1,"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":null}

[]
```

**Comment by idealvin** [comment]
> 不好意思，在构建最小代码时没注意检查。以下是经检查后的代码：
> 
> ```c++
> #include "co/json.h"
> 
> int main() {
>   auto v = json::parse("[{\"1\":1,\"2\":2,\"3\":3,\"4\":4,\"5\":5,\"6\":6,\"7\":7}]");
>   Json i = v[0];
>   i["8"];
>   printf("%s\n", i.str().c_str());
>   printf("%s\n", v[0].str().c_str());
>   printf("%s\n", v.str().c_str());
>   return 0;
> }
> ```
> 
> 这个问题的特殊点在于`object`的属性必须为7个(更多的我没试过，估计与内存分配算法有关)。
> 在第7行输出`i.str()`时是正常的，但后面的代码就不正常了。以上代码的输出结果如下：
> 
> ```
> {"1":1,"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":null}
> 
> []
> ```

这个问题的原因是，Json i = v[0],  i 和 v[0] 在内部有一个相同的指针，指向一块共享的内存，
但 i[8] 这个操作导致 i 内部重新分配了内存，v[0] 原先的那个指针失效了。

在这种情况下，建议将 Json i = v[0] 改成
```cpp
Json& i = v[0];
```

**Comment by tigerlee** [comment]
我在实际使用中改成了先用`has_member()`判断再访问。
既然有这个问题存在，而文档上并没有禁止这种做法，总感觉应该做点什么来从源头避免这个问题。 :smile:

**Comment by idealvin** [comment]
> 我在实际使用中改成了先用`has_member()`判断再访问。
> 既然有这个问题存在，而文档上并没有禁止这种做法，总感觉应该做点什么来从源头避免这个问题。 😄

可以的，底层分配两块内存可以解决这个问题，但性能会下降一些，武汉疫情稳定些再考虑重构这一块

**Comment by idealvin** [comment]
@tigerlee  dev 分支试着修复了这个问题，可以验证下？

**Comment by tigerlee** [comment]
验证通过，没问题了。
