### ISSUE TITLE
关于 C++11 特性的考虑

### ISSUE THREAD

**Issue by frederick-vs-ja** [idealvin/co#5]
目前看来这些代码并没有按照 C++11 前和 C++11 开始条件编译。假如这是有意的，那么我认为有些细节实现应当继续改进：

- `def.h` 应当直接使用 `<cstdint>` 或者 `<stdint.h>` 。其他代码应该直接使用 `(u)intN_t` 以减少冲突。
- 应该使用标准的 `thread_local` 代替 `__thread` 。
- 原子对象应当使用 `<atomic>` 。
- `swap` 函数和移动特殊成员函数应当加上 `noexcept` 。
（以及其他可能存在的问题）

**Comment by idealvin** [comment]
前面三个应该只是使用习惯问题，最后那个加 noexcept 的建议，倒是可以引进来，可以帮忙提个pr
