### ISSUE TITLE
vs 2019 16.4.5 (使用 Unicode 字符集) 下怎么编译？

### ISSUE THREAD

**Issue by sgf** [idealvin/co#54]
vs2015那个文件夹的sln编译不过。

我尝试删除一些依赖，但是因为context文件夹下有一些汇编文件不带明白，不敢乱动。

**Comment by idealvin** [comment]
> vs2015那个文件夹的sln编译不过。
> 
> 我尝试删除一些依赖，但是因为context文件夹下有一些汇编文件不带明白，不敢乱动。

@sgf 
vs 工程是早期提供的，采用多字节编码应该是可以编过的。

建议使用 xmake 编译，vs 工程后续可能不再支持。

**Comment by sgf** [comment]
> vs 工程是早期提供的，采用多字节编码应该是可以编过的。
> 建议使用 xmake 编译，vs 工程后续可能不再支持。
后续项目不会再用多字节编码了。我自己再倒腾一下，用不了就算了。

**Comment by idealvin** [comment]
@sgf 你可以先试试直接改下工程属性，多字节改为unicode编码，代码实现应该是不依赖这个的

**Comment by sgf** [comment]
可以了 谢谢！是x64和x86 asm文件条件编译问题。

**Comment by idealvin** [comment]
@sgf 

ok. 如果一定要 vs 工程的话，也可以用 xmake 自动生成:

```sh
xmake project -k vsxmake -m "debug;release"
```
