### ISSUE TITLE
Lru 实现

### ISSUE THREAD

**Issue by ktprime** [idealvin/co#58]
插入发现存在是不是调整一下位置到头部?
list用了2个使用一个效率会更好一点?
//一般插入实现大致这样

	void put(const Key& key,const Value& value){
		const auto iter = _cache.find(key);
		if(iter!= _cache.end()){
			// 找到了就更新value，并提取到最前面
			iter->second->value = value;
			//move iter->second to _keys' begin postion
			_keys.splice(_keys.begin(),_keys,iter->second);
			return;
		}
		_keys.emplace_front(key,value);
		_cache[key] = _keys.begin();
		resize();
	}

**Comment by idealvin** [comment]
@ktprime 
1、find, insert 已经调整到头部
2、使用两个，是 erase 操作所需要的，std::list 只能根据iterator删除，因此加了一个map，保存key对应的iterator.

后续可能考虑降低 erase 操作的要求

**Comment by idealvin** [comment]
@ktprime 
后面考虑修改下 插入存在的逻辑。
使用两个主要是方便 iterator 操作，跟 std::map 行为保持一致。

**Comment by ktprime** [comment]
我测试一个list的实现性能可以提升10%左右 

测试我的lru实现, 简单数据类型比如整数k.v和你的对比
写入 8-10倍,
读取 4-8倍.
删除和迭代6-10倍  

bench程序在 https://github.com/ktprime/emhash/blob/master/bench/lru_test.cpp.
实现就一个数组, 如果size设置足够大当hash map 使用.

设计上是满了之后淘汰一半空间(略有有点卡顿,  100w 整数k.v空间删除一般大概20-30ms),
 和正统lru实现有点差异. 还在继续调优 通用性还存在一些问题, 目前在公司使用内存大幅度降低

**Comment by ktprime** [comment]
size = 1642239
3.random data
loop 1 size 1642239
    my insert time = 99 ms
    my find 1642239 hit time = 58 ms
    my find half time = 59 ms

    co insert time = 1453 ms
    co find 1642239 time = 397 ms
    co find half time = 391 ms
    ============================
loop 2 size 3284478
    my insert time = 269 ms
    my find 3284478 hit time = 129 ms
    my find half time = 135 ms

    co insert time = 3055 ms
    co find 1642898 time = 493 ms
    co find half time = 483 ms
    ============================
loop 3 size 4926717
    my insert time = 422 ms
    my find 2147883 hit time = 114 ms
    my find half time = 130 ms

    co insert time = 7420 ms
    co find 1643500 time = 560 ms
    co find half time = 643 ms
    ============================
loop 4 size 6568956
    my insert time = 985 ms
    my find 3063651 hit time = 162 ms
    my find half time = 200 ms

    co insert time = 9913 ms
    co find 1644048 time = 650 ms
    co find half time = 693 ms
    ============================
loop 5 size 8211195
    my insert time = 1103 ms
    my find 2847724 hit time = 213 ms
    my find half time = 229 ms

    co insert time = 12385 ms
    co find 1644804 time = 767 ms
    co find half time = 858 ms
    ============================

**Comment by idealvin** [comment]
@ktprime 
非常感谢你的反馈，后续考虑优化一下.

**Comment by idealvin** [comment]
通用性不强，暂不考虑.
