### ISSUE TITLE
Document that fastring is not thread-safe

### ISSUE THREAD

**Issue by snej** [idealvin/co#59]
The implementation of `fastring` is not thread-safe. That’s fine, but people might get in trouble if they don’t know this, since std::string is thread-safe. So it would be good to point this out in the documentation.

(Making `fastring` thread safe is probably not a good idea. I’ve read that `std::string` used to use ref-counting and copy-on-write the way yours does, but the atomic operations or mutexes needed to make it thread-safe hurt performance a lot, and it’s actually faster for it to always copy.)

**Comment by idealvin** [comment]
@snej 
- Copying `fastring` is thread-safe like the `std::string`. 
- `copy-on-write` is not used in `fastring`.

**Comment by idealvin** [comment]
Hi, Jens, thanks for your&nbsp;suggestion.
I'll update the documents later. A little busy for these days..



---Original---

**Comment by idealvin** [comment]
@snej 
Hi, Jens, the [document for fastring](https://github.com/idealvin/co/blob/master/docs/en/08.efficient_strings(fastring).md) already said about it. See `Special Notes` in the document:

```cpp
fastring s = "xx";
fastring t = s;   // s, t points to the same string
t + = 'x';        // s, t-> "xxx"
t = "888";        // s, t-> "888"

fastring r = "r";
t = r;            // t-> "r", s is still "888", only the reference count is decremented by 1

fastring x;       // empty string, no memory allocated
fastring y = x;   // x and y do not share memory since no memory is allocated
y = "yy";         // y -> "yy", x is still empty
```

I'm not sure if it is clear enough. You may help to improve it?

**Comment by snej** [comment]
That section helps, but it only tells half the story. If the shared string storage were thread-safe [the way std::string was long ago] there would not be concurrency issues. So the other half of the story is to point out that it's not thread-safe.

I suggest adding a section like:

>**Warning** for multi-threaded use: Strings should never be shared between threads that might modify them, because the operations that mutate string storage are not thread-safe. To safely pass a string from one thread to another, call its `clone` method, which creates an entirely separate `fastring` with its own copy of the storage.

**Comment by idealvin** [comment]
> That section helps, but it only tells half the story. If the shared string storage were thread-safe [the way std::string was long ago] there would not be concurrency issues. So the other half of the story is to point out that it's not thread-safe.
> 
> I suggest adding a section like:
> 
> > **Warning** for multi-threaded use: Strings should never be shared between threads that might modify them, because the operations that mutate string storage are not thread-safe. To safely pass a string from one thread to another, call its `clone` method, which creates an entirely separate `fastring` with its own copy of the storage.

@snej OK. Thanks. I' ll do it later.

**Comment by idealvin** [comment]
I'll document it at the next release.

**Comment by idealvin** [comment]
@snej  I have removed reference counting from `fastring`. Now it has a similar copying behavior to `std::string`.
