### ISSUE TITLE
fastring: 多线程问题与内存管理问题

### ISSUE THREAD

**Issue by frederick-vs-ja** [idealvin/co#6]
1. `fastring` 类的引用计数未使用原子对象。这显然会造成多线程同时修改时的数据竞争。希望作者注明这种设计是否有意的。
2. `fastring` 类的内存分配、释放函数是不能替换的。我认为替换全局的 `operator new` 和 `operator delete` 是在一定应用条件下提高性能的做法，但 `fastring` 并不能从中受益。

**Comment by idealvin** [comment]
第一个问题这两天在考虑中，fastring 在多线程环境下复制确实不安全，应该用原子操作，调用 base/atomic.h 提供的 atomic_inc 与 atomic_dec 即可。可以提一个 PR。

 Json 中的引用计数也没有使用原子操作，则是出于性能上的考虑，一般不会在多线程中复制 Json 对象。

第二个问题可能不需要考虑，推荐使用 jemalloc 进行内存优化。

**Comment by idealvin** [comment]
替换全局的 operator new，operator delete，使用 jemalloc, tcmalloc 这类库应该就可以了

**Comment by lhmouse** [comment]
allocator 显然应该是可替换的，标准库的容器几乎都支持（除了 `std::array` 以外）。

`fastring` 的问题多了去了，不如用 [`rocket::cow_string`](https://github.com/lhmouse/asteria/blob/03457491045fa15262bf65bc586b0b8529ded321/asteria/rocket/cow_string.hpp#L261) 吧（逃
