### ISSUE TITLE
Is the epoll implements support only 1024 fd?

### ISSUE THREAD

**Issue by hgoldfish** [idealvin/co#62]
If the `fd` value greater than `1024`, this line would lead to overflow error:

    // from base/co/impl/epoll.cc
    int& x = _ev_map[fd];

**Comment by idealvin** [comment]
> If the `fd` value greater than `1024`, this line would lead to overflow error:
> 
> ```
> // from base/co/impl/epoll.cc
> int& x = _ev_map[fd];
> ```

Hi, the number of fd is unlimited. The _ev_map is a map, not an array.
