### ISSUE TITLE
recv(sock_t fd, void* buf, int n, int ms)超时后程序崩溃

### ISSUE THREAD

**Issue by gitchenqw** [idealvin/co#65]
recv(sock_t fd, void* buf, int n, int ms)超时后程序崩溃

**Comment by idealvin** [comment]
> recv(sock_t fd, void* buf, int n, int ms)超时后程序崩溃

请提供详细的信息.

**Comment by idealvin** [comment]
你可能用的是老代码，请用 master 分支最新代码.

**Comment by idealvin** [comment]
@gitchenqw 
Windows 上确实有个 io 超时引起的 bug，有一种情况，io 超时与 io 事件同时到达，处理 io 超时会调用 windows 的 CancleIO，但 io 完成事件刚好在 CancleIo 之前放到内部队列中。这种情况导致程序崩溃，已在[#96 ](https://github.com/idealvin/co/commit/034c070e9c1b6fa5cf2c9bc5b6410b0993c12d72) 中修复。
