### ISSUE TITLE
tcp_test.cc中go(client_fun)改为如下代码后在vs2019中运行报read access violation

### ISSUE THREAD

**Issue by xwpcom** [idealvin/co#70]
for (int i = 0; i < 1000*10; i++)
    {
        go(client_fun);
    }

**Comment by idealvin** [comment]
@xwpcom 

> for (int i = 0; i < 1000*10; i++)
> {
>     go(client_fun);
> }


client_fun() 中的 COUT 是打印到终端，非线程安全，可以将 COUT 换成 LOG，再测试一下

**Comment by idealvin** [comment]
另外在 main() 函数开头加上:
```cpp
    flag::init(argc, argv);
    log::init();
```

**Comment by xwpcom** [comment]
改用LOG后问题消失，多谢
int main(int argc, char** argv) {
    flag::init(argc, argv);

    log::init();

    go(server_fun);
    sleep::ms(32);

    for (int i = 0; i < 1; i++)
    {
        go(client_fun);
    }

    while (true) {
        sleep::sec(3);

        co::stop();
        break;
    }

    return 0;
}

是在代码中加了 co::stop();才发现这个问题的
我觉得不管是服务器，还是客户端，都必须能干净的退出，这点非常重要。

**Comment by idealvin** [comment]
`co::stop`不能在这个地方调用，一般是程序退出时调用



---原始邮件---
发件人: "BearOnePing"<notifications@github.com&gt;
发送时间: 2020年6月22日(周一) 上午9:19
收件人: "idealvin/co"<co@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Alvin"<idealvin@qq.com&gt;;
主题: Re: [idealvin/co] tcp_test.cc中go(client_fun)改为如下代码后在vs2019中运行报read access violation (#70)




 
改用LOG后问题消失，多谢
 int main(int argc, char** argv) {
 flag::init(argc, argv);
 log::init(); go(server_fun); sleep::ms(32); for (int i = 0; i < 1; i++) {     go(client_fun); } while (true) {     sleep::sec(3);     co::stop();     break; } return 0;  
}
 
是在代码中加了 co::stop();才发现这个问题的
 我觉得不管是服务器，还是客户端，都必须能干净的退出，这点非常重要。

**Comment by idealvin** [comment]
你的代码中，3秒就stop了，协程就没法工作了



---原始邮件---
发件人: "BearOnePing"<notifications@github.com&gt;
发送时间: 2020年6月22日(周一) 上午9:19
收件人: "idealvin/co"<co@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Alvin"<idealvin@qq.com&gt;;
主题: Re: [idealvin/co] tcp_test.cc中go(client_fun)改为如下代码后在vs2019中运行报read access violation (#70)




 
改用LOG后问题消失，多谢
 int main(int argc, char** argv) {
 flag::init(argc, argv);
 log::init(); go(server_fun); sleep::ms(32); for (int i = 0; i < 1; i++) {     go(client_fun); } while (true) {     sleep::sec(3);     co::stop();     break; } return 0;  
}
 
是在代码中加了 co::stop();才发现这个问题的
 我觉得不管是服务器，还是客户端，都必须能干净的退出，这点非常重要。
