### ISSUE TITLE
arm gcc编译器无法通过编译, 需要将char 改成int8_t

### ISSUE THREAD

**Issue by mosxuqian** [idealvin/co#77]
index 9d2a6e3..c09f622 100644
--- a/src/hash/base64.cc
+++ b/src/hash/base64.cc
@@ -3,7 +3,7 @@
 static const char* entab =
     "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

-static const char detab[256] = {
+static const int8_t detab[256] = {
     -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
     -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
     -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 62, -1, -1, -1, 63,

**Comment by idealvin** [comment]
> index 9d2a6e3..c09f622 100644
> --- a/src/hash/base64.cc
> +++ b/src/hash/base64.cc
> @@ -3,7 +3,7 @@
> static const char* entab =
> "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
> 
> -static const char detab[256] = {
> +static const int8_t detab[256] = {
> -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
> -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
> -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 62, -1, -1, -1, 63,

@mosxuqian 
-1 转换为 char 时，有些编译器好像确实会报警，没有深究。
我先改成 int8_t 吧.  (int8_t 与 char 在很多平台没有区别的吧？)

**Comment by idealvin** [comment]
@mosxuqian 
已经改成了 `int8`，你可以用 master 分支代码再试下

**Comment by waruqi** [comment]
还是不要用char的好，arm下char默认是unsigned，但是有些平台 比如ios上，默认char是 signed  ，用在-1上容易出问题，即使能编译过。。

**Comment by idealvin** [comment]
> 还是不要用char的好，arm下char默认是unsigned，但是有些平台 比如ios上，默认char是 signed ，所以不同平台上直接用char在-1上容易出问题，即使能编译过。。

@waruqi 哦，是这样，对 arm 平台不熟，多谢了 😄
