### ISSUE TITLE
What's the difference between your mutex, thread libraries and those in standard library?

### ISSUE THREAD

**Issue by yxtj** [idealvin/co#79]
请问co中的mutex, thread等库在c++11和以后的标准库中都有对应的版本，它们的区别是什么？
我在开发的过程中应该如何选择？

**Comment by idealvin** [comment]
> 请问co中的mutex, thread等库在c++11和以后的编制库中都有对应的版本，它们的区别是什么？
> 我在开发的过程中应该如何选择？

@yxtj 
都可以用，没有冲突

**Comment by yxtj** [comment]
> > 请问co中的mutex, thread等库在c++11和以后的编制库中都有对应的版本，它们的区别是什么？
> > 我在开发的过程中应该如何选择？
> 
> @yxtj
> 都可以用，没有冲突

那co中的这几个库是不是冗余的？

**Comment by idealvin** [comment]
不算冗余，这些是 C++ 提供 `std::mutex`, `std::thread` 之前开发的

**Comment by yxtj** [comment]
我的意思是，现在既然c++已经提供了这些标准库，为了代码的可读性和以后的维护，特别是开源合作的情况下，是不是应该考虑用标准库替换掉？

**Comment by idealvin** [comment]
@yxtj 
目前不能删，co 内部有依赖
