### ISSUE TITLE
lrumap

### ISSUE THREAD

**Issue by ktprime** [idealvin/co#8]
你的是标准传统的实现. 大多数业务场景不要这么强的顺序和严格容量限制(稍微超一点),
我的实现 https://github.com/ktprime/emhash/blob/master/lru_size.h
只用一个数组, 乐观估计比你的快10倍(有空我测试一下).

**Comment by lhmouse** [comment]
1. [difference_type](https://github.com/ktprime/emhash/blob/bbe17cf00223d1d6147a7d547d974215c6214912/lru_size.h#L220) 必须是有符号类型。
2. 上面 iterator 的 `value_type` 成员没有（是否是故意的）。
3. [内置 `&` 可重载](https://github.com/ktprime/emhash/blob/bbe17cf00223d1d6147a7d547d974215c6214912/lru_size.h#L190)，应该换成 `::std::addressof()`。
4. [`malloc()` 应该换成 `::operator new()`](https://github.com/ktprime/emhash/blob/bbe17cf00223d1d6147a7d547d974215c6214912/lru_size.h#L297)；当然，不支持 allocator 嘛，呵呵。
5. [move constructor 不是 noexcept 的](https://github.com/ktprime/emhash/blob/bbe17cf00223d1d6147a7d547d974215c6214912/lru_size.h#L301)，不过你这个实现和 libstdc++ 的 `std::deque` 一样，不支持。
6. [`std::is_pod`](https://github.com/ktprime/emhash/blob/bbe17cf00223d1d6147a7d547d974215c6214912/lru_size.h#L357) 建议换成 `std::is_trivially_copyable`。
7. [`swap` 应该透过 ADL 调用](https://github.com/ktprime/emhash/blob/bbe17cf00223d1d6147a7d547d974215c6214912/lru_size.h#L371)。
8. [为什么一会是 `size_type` 一会是 `uint32_t`](https://github.com/ktprime/emhash/blob/bbe17cf00223d1d6147a7d547d974215c6214912/lru_size.h#L419) ？
9. [注释写的 `nullptr` 实际返回的是 `bool` 类型](https://github.com/ktprime/emhash/blob/bbe17cf00223d1d6147a7d547d974215c6214912/lru_size.h#L631)。
10. [return by value 的不要写 `const`](https://github.com/ktprime/emhash/blob/bbe17cf00223d1d6147a7d547d974215c6214912/lru_size.h#L657)。
11. [`find` => `found`](https://github.com/ktprime/emhash/blob/bbe17cf00223d1d6147a7d547d974215c6214912/lru_size.h#L686)。
12. [`emplace()` 系列都是 CopyInsert 不是 EmplaceInsert](https://github.com/ktprime/emhash/blob/bbe17cf00223d1d6147a7d547d974215c6214912/lru_size.h#L784) 。
13. [`operator[] ()` 不应该是 `noexcept` 因为可能是插入新值](https://github.com/ktprime/emhash/blob/master/lru_size.h#L830)
14. [`erase(iterator)` 的重载多余](https://github.com/ktprime/emhash/blob/bbe17cf00223d1d6147a7d547d974215c6214912/lru_size.h#L882)，只应该有 `erase(const_iterator)`，不应该返回 `void`。
15. [`shrink_to_fit()`](https://github.com/ktprime/emhash/blob/bbe17cf00223d1d6147a7d547d974215c6214912/lru_size.h#L924) 不应该是 `noexcept`。
16. [hash function 和  key equality predicate 直接存成员的话会占内存](https://github.com/ktprime/emhash/blob/master/lru_size.h#L1247)，没有 EBO，建议做成基类（需要注意 `final` 的情况）。

**Comment by ktprime** [comment]
建议不错 改掉存在的一些问题 我的是flat_map

**Comment by FrankHB** [comment]
* 你的代码没有如声称所谓的被 [dual-licensed](https://github.com/ktprime/emhash/blob/master/lru_size.h#L6) 因为 public domain 不是许可证。使用 CC0 、WTFPL 或者其它能被称为许可证的代替。
* 这里的宏污染意义何在？你没忘记你这里是头文件吧？
* 既然都[用了 `<cstdint>`](https://github.com/ktprime/emhash/blob/master/lru_size.h#L30) ，为什么 `uint32_t` 没 `std` ？
* 既然你[都 `&&`](https://github.com/ktprime/emhash/blob/master/lru_size.h#L73) 了（和 <cstdint> 说明打算依赖 C++11 ），那么为什么无视了一大堆能加 `noexcept` 的地方？
* 为什么 `entry` 构造函数不写成转发模板？
* 似乎完全无视了 `std::piecewise_construct` ？
* 为什么[这里](https://github.com/ktprime/emhash/blob/master/lru_size.h#L521)用 `int` ？
* 为什么[这里](https://github.com/ktprime/emhash/blob/master/lru_size.h#L523-L524)用的是 `size_t` 而不是 `std::uintptr_t` ？

**Comment by ktprime** [comment]
很多细节问题还没做好, 值得反思一直在优化性能, 你说的这些慢慢不上吧

std::is_pod 建议换成 std::is_trivially_copyable。 这个为了兼容c++0x(gcc 4.6.x)
那些宏会后面去掉, c++模板还不是很熟悉
