### ISSUE TITLE
udpsocket  co::close无法让co::recvfrom跳出等待

### ISSUE THREAD

**Issue by mosxuqian** [idealvin/co#98]
co::close 触发了del_event(ev)
但是co::recvfrom等待的EV_read 消息订阅被删除，但是recvfrom仍然在等待。

解决方法：
1、或许可以加入EV_close/EV_ignore之类的事件。
2、IoEvent加入多事件绑定，同时绑定EV_read和EV_close/EV_ignore。

**Comment by idealvin** [comment]
@mosxuqian 
能贴上你的代码，看看你怎么用的？

**Comment by idealvin** [comment]
由send方调用close()，recv方才能退出等待，正常的socket编程就是这样的

**Comment by mosxuqian** [comment]
co::recvfrom如果想等的udp数据没发过来，程序内部需要想终止udp接收，但不想退出整个进程。

这个时候无法做到结束udp_server_fun协程。

目前可以用recvfrom加上timeout来绕开无法结束的问题，但这并没有直接解决问题。

**Comment by idealvin** [comment]
@mosxuqian 

有下面几点要注意的：

- `co::close(fd)` 与 `co::recvfrom(fd...)` 必须在同一个线程中调用（一般最好在同一个协程中）
- send 方调用 close()，recv 方才能收到相应的事件，退出等待
- recv 方不想无限等待，可以加个超时时间: `recvfrom(fd..., ms)`

[参考文档](https://github.com/idealvin/co/blob/master/docs/cn.md#1641-%E5%B8%B8%E7%94%A8%E7%9A%84-socket-api)
[代码示例](https://github.com/idealvin/co/blob/master/test/so/udp.cc)

**Comment by idealvin** [comment]
> co::recvfrom如果想等的udp数据没发过来，程序内部需要想终止udp接收，但不想退出整个进程。
> 
> 这个时候无法做到结束udp_server_fun协程。
> 
> 目前可以用recvfrom加上timeout来绕开无法结束的问题，但这并没有直接解决问题。

@mosxuqian 
加超时时间就是正解

**Comment by idealvin** [comment]
@mosxuqian 
你可以参考 [rpc::Server, http::Server](https://github.com/idealvin/co/tree/master/src/so) 的源码，server 端 recv 一般都需要加超时时间的.

**Comment by mosxuqian** [comment]
加超时有性能(非常少)开销，逻辑代码也多了：
            if (ETIMEDOUT == co::error()) {
                continue;
            }
多出来的这段代码很丑。

**Comment by mosxuqian** [comment]
需求场景是这样的，
正常情况下，要求一直等到，收到请求做业务处理。可能就这样一直跑1天，这一天内只收到10个请求，但是超时逻辑代码却要执行数万次。
但是1天以后用户想关掉这个udp服务。

**Comment by idealvin** [comment]
......

**Comment by idealvin** [comment]
> 需求场景是这样的，
> 正常情况下，要求一直等到，收到请求做业务处理。可能就这样一直跑1天，这一天内只收到10个请求，但是超时逻辑代码却要执行数万次。
> 但是1天以后用户想关掉这个udp服务。

几万次判断根本就没什么开销，每次消耗几微秒，一天几万次才几十毫秒，一般不需要考虑的

**Comment by idealvin** [comment]
实在不想频繁判断，超时时间可以设长点，如 1 分钟

**Comment by mosxuqian** [comment]
开销是微小的，还有一个缺点刚才没说，无法及时响应关闭事件。假如超时时间设为1秒，关闭是需要等待recv的1秒超时。

1、超时逻辑处理开销。
2、响应度降低。
3、代码不够优雅。

这三个缺点，对应大部分用户来讲，都不是什么问题。但是作为一个架构长远看还是要解决的。加油！！

**Comment by idealvin** [comment]
> 开销是微小的，还有一个缺点刚才没说，无法及时响应关闭事件。假如超时时间设为1秒，关闭是需要等待recv的1秒超时。
> 
> 1、超时逻辑处理开销。
> 2、响应度降低。
> 3、代码不够优雅。
> 
> 这三个缺点，对应大部分用户来讲，都不是什么问题。但是作为一个架构长远看还是要解决的。加油！！

@mosxuqian 
`EV_close/EV_ignore` 之类的，epoll/kevent/iocp 本身就不支持，这些没有办法加。  

另外，从 server 可靠性考虑，server 端 recv 一般必须要加超时，主要是为了：  

> 连接过多时，server 端可以主动断掉一些空闲连接。

**Comment by idealvin** [comment]
@mosxuqian 

这是个机制问题，暂不考虑支持。

- 用原生的 socket api，也不可能通过主动调用 close()，使 block 状态的 recv() 等操作立即得到响应。
- 协程一般采用同步的编码方式，对于同一个 socket，recv, send, close 等操作一般在同一个协程中完成。
- 按 co 目前的实现方式，close 与 recv(send) 必须在同一个线程中调用，主要是为了简化内部逻辑，尽量避免多线程带来的复杂性。

可以参考 [tcp::Client](https://github.com/idealvin/co/blob/master/include/co/so/tcp.h#L82) 的实现，里面特意加了:

```cpp
assert(_sched_id == co::sched_id());
```

就是为了禁止用户直接在其他线程关闭 socket 的操作.
